### ISSUE TITLE
Support for language parameter

### ISSUE THREAD

**Issue by edwinbs** [ubilabs/react-geosuggest#100]
Please add support for the optional `language` parameter as supported by the Google Place Autocomplete.

> `language` — The language in which to return results. See the supported list of domain languages. Note that we often update supported languages so this list may not be exhaustive. If language is not supplied, the Place Autocomplete service will attempt to use the native language of the domain from which the request is sent.

**Comment by ro-ka** [comment]
That param is not supported. This component uses the `google.maps.places.AutocompleteService.getPlacePredictions` call. See the [reference](https://developers.google.com/maps/documentation/javascript/reference?csw=1#AutocompletionRequest) for allowed params.

**Comment by edwinbs** [comment]
Thanks for the link, found out from there that the way is to use:

`<script src="https://maps.googleapis.com/maps/api/js?libraries=places&language={language}"></script>`

**Comment by davidlewisbates1980** [comment]
> That param is not supported. This component uses the `google.maps.places.AutocompleteService.getPlacePredictions` call. See the [reference](https://developers.google.com/maps/documentation/javascript/reference?csw=1#AutocompletionRequest) for allowed params.

Am I missing something? It looks like the `language` parameter is there...

<img width="704" height="140" alt="Image" src="https://github.com/user-attachments/assets/fab20e3f-2846-4974-a6e7-74ab66eb5668" />

**Comment by davidlewisbates1980** [comment]
> Thanks for the link, found out from there that the way is to use:
> 
> `<script src="https://maps.googleapis.com/maps/api/js?libraries=places&language={language}"></script>`

Even when I set the language...

<img width="397" height="212" alt="Image" src="https://github.com/user-attachments/assets/eb4af9a7-e664-4a82-93ab-bee358c4f011" />

...not all results come back in the specified language:

<img width="2910" height="1048" alt="Image" src="https://github.com/user-attachments/assets/dc857422-dd84-4304-bef5-8226aa2c35f3" />

Is it just not good enough to know that "London" in French is "Londres"?

**Comment by ro-ka** [comment]
Hi, the ticket is 9.5 years old, so maybe the Google Maps API changed in the meantime. I’m not maintaining this anymore and I did not use the Maps API in the past ~5 years. Looking at the recent commits, maybe @yfr or @nilsingwersen from Ubilabs can help you.
