### ISSUE TITLE
Pressing enter does not fill in the input

### ISSUE THREAD

**Issue by cricque** [ubilabs/react-geosuggest#102]
So when you for instance type an entire adress like

MyStreet 24 MyLocation

When you press enter nothing happens instead of picking the first entry (most likely only) in the list
Is there a way to implement this behavior ?

**Comment by ro-ka** [comment]
So do you have suggestions in the list for the entered string? Or is it empty? Do you expect to select the first entry of the list or do you expect to geocode the entered string and use that?

**Comment by cricque** [comment]
Well I for instance type "Zaventem" and the first entry in the suggestion list is the one I want, when you press on enter I think it should take the first suggestion. And in onSuggestSelect that entry should be forwarded then 

But for the rest a good component and works really wel & fast 



----- Oorspronkelijk bericht -----

Van: "Robert Katzki" <notifications@github.com> 
Aan: "ubilabs/react-geosuggest" <react-geosuggest@noreply.github.com> 
Cc: "cricque" <cricque@telenet.be> 
Verzonden: Vrijdag 11 maart 2016 09:13:58 
Onderwerp: Re: [react-geosuggest] Pressing enter does not fill in the input (#102) 



So do you have suggestions in the list for the entered string? Or is it empty? Do you expect to select the first entry of the list or do you expect to geocode the entered string and use that?

**Comment by ro-ka** [comment]
Is [`autoActivateFirstSuggest`](https://github.com/ubilabs/react-geosuggest#autoactivatefirstsuggest) doing what you’re looking for?

**Comment by ro-ka** [comment]
Closing as there is no further feedback.
