### ISSUE TITLE
Google Places API : Types Deprecation

### ISSUE THREAD

**Issue by Victordmdb** [ubilabs/react-geosuggest#106]
As per [google places docs ]( https://developers.google.com/maps/documentation/javascript/places-autocomplete):

"The types parameter is deprecated as of February 16, 2016, replaced by a new type parameter which only supports one type per search request".

**Comment by Victordmdb** [comment]
After further research I discovered the Autocomplete feature DOES NOT support all types as listed in the [Places API Types](https://developers.google.com/places/supported_types#table1), but instead [can only support] : ''establishment' for businesses, 'geocode' for addresses, '(regions)' for administrative regions and '(cities)' (https://developers.google.com/maps/documentation/javascript/reference#AutocompletionRequest)

**Comment by ro-ka** [comment]
Reopening as you didn’t intent to close, right?

**Comment by ro-ka** [comment]
The [AutocompletionRequest](https://developers.google.com/maps/documentation/javascript/reference#AutocompletionRequest) doesn’t show these deprecations and changes.

I’ll keep this open to recheck soon if the docs got updated.

**Comment by 29er** [comment]
Yes, I can confirm that the latest API only supports 'establishment' for business'. you can't put in 'restuarant' , 'bar' etc.

**Comment by ro-ka** [comment]
So the documentation states this:
> Four types are supported: 'establishment' for businesses, 'geocode' for addresses, '(regions)' for administrative regions and '(cities)' for localities. If nothing is specified, all types are returned.

As there was no update I suspect it isn’t affected by other API changes.
