### ISSUE TITLE
Google Maps API warning: NoApiKeys

### ISSUE THREAD

**Issue by tyrants** [ubilabs/react-geosuggest#107]
Hello,

Warning since few days :

Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

**Comment by dyba** [comment]
@tyrants [Google's Place Autocomplete API documentation](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete) states that you need to include your API key in the script tag:

``` 
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
```

**Comment by tyrants** [comment]
Oh my bad, I thought it was a script call Included in the package -_-

**Comment by ro-ka** [comment]
Thanks for bringing this up as the example needs an update.  :)
Will reopen to have this as a todo.

And thanks for clarifying, @dyba.

**Comment by balogic** [comment]
@dyba Is there any option to do it in the `npm` way. We can't use script tag there

**Comment by ro-ka** [comment]
@balogic You have to pass it to your Google Maps instance when initializing. This component can get the Google Maps instance via a property [googleMaps](https://github.com/ubilabs/react-geosuggest#googlemaps). How to pass it in depends on the component you’re using for the Google Map.
