### ISSUE TITLE
value not updated when suggestion selected

### ISSUE THREAD

**Issue by cagarweyne** [ubilabs/react-geosuggest#108]
The value is not updated in the input field when you select a suggestion from the dropdown menu. I changed this in the component to call the `this.props.onChange` function inside the `selectSuggest` function as a callback after the state is updated. I'm just wondering if this should be default behavior? Here's the code I'm referring to:

```javascript 
  selectSuggest(suggest) {
    if (!suggest) {
      suggest = {
        label: this.state.userInput
      };
    }

    this.setState({
      isSuggestsHidden: true,
      userInput: suggest.label
    }, () => { this.props.onChange(suggest.label) });

    if (suggest.location) {
      this.setState({ignoreBlur: false});
      this.props.onSuggestSelect(suggest);
      return;
    }

    this.geocodeSuggest(suggest);
  
```

**Comment by ro-ka** [comment]
Can you provide a test case on Codepen or Jsbin or similar? When do the suggests not get selected?

**Comment by amitthakkar22288** [comment]
when i use my laptop touchpad and the inbuilt mousekeys the click event is never fired. 
i was able to replicate this quite a few times using the normal mouse too.

**Comment by ro-ka** [comment]
I cannot replicate this, sorry. Please provide a test case and reopen the issue.
