### ISSUE TITLE
Support passing in styles prop?

### ISSUE THREAD

**Issue by esauter5** [ubilabs/react-geosuggest#109]
Thanks for the great work on this project!

I tend to use inline styles with React. Would you be willing to support passing an optional `styles` prop to `Geosuggest` that would support overriding/adding styles to the various components that make it up? If so, I'd be willing to work on a PR to support this.

**Comment by ro-ka** [comment]
You can definitely work on a PR!

Just lets define the params first. Not sure how it works in other modules, as we use CSS for styling. ;) Would a `style` object enough? That can contain `input`, `suggests` and `suggest-item`, right?

**Comment by esauter5** [comment]
@ro-ka that's exactly what I was thinking!

**Comment by ro-ka** [comment]
Perfect, then go for it! :)

**Comment by 29er** [comment]
@esauter5 Just wondering if you made progress on this ? This is exactly what Im looking for !
thanks

**Comment by narendrashetty** [comment]
@ro-ka I have sent a PR for the above enhancement. Hope it works.

**Comment by narendrashetty** [comment]
@ro-ka we need to mention about this feature in the docs.
