### ISSUE TITLE
Broken Example In Repo

### ISSUE THREAD

**Issue by dyba** [ubilabs/react-geosuggest#112]
## What I did

* Clone the repository
* Ran ```npm install```
* Ran ```npm start```

## What I expected

* A working Geosuggest example at http://localhost:8000

## What actually happened

![screen shot 2016-03-29 at 10 13 15 pm](https://cloud.githubusercontent.com/assets/296219/14132507/7cc02e20-f5fb-11e5-850c-07fdaa07620a.png)

And using the debugger...

![screen shot 2016-03-29 at 10 28 10 pm](https://cloud.githubusercontent.com/assets/296219/14132703/9b2dce10-f5fd-11e5-9955-9ed23c5ff46d.png)

Led me to think that the reason it wasn't working was because I needed to add NODE_ENV=production to the ```npm start``` command; however, that just gives me a minified error.

**Comment by ro-ka** [comment]
Thanks for reporting! :+1: for providing detailed information!

I can reproduce this, but have no idea why that is happening…

**Comment by Scarysize** [comment]
Seems to be a problem with the `require('Geosuggest')` statement in the example `app.js`. If you replace it with: `import Geosuggest from '../../src/Geosuggest';` the example works.

**Comment by Scarysize** [comment]
Here is an explanation for the problem (babel 6 is the cause): http://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x
