### ISSUE TITLE
Possible to return name with the gmaps object?

### ISSUE THREAD

**Issue by larawarman** [ubilabs/react-geosuggest#113]
We get the formatted address, but is it possible to return the other location details (specifically name) as a part of the gmaps object?

**Comment by ro-ka** [comment]
The `gmaps` object is returned directly from the Google result – there isn’t any data filtered out. To get more information, use the `placeId` and request more info from Google with a [GeocoderRequest](https://developers.google.com/maps/documentation/javascript/reference#GeocoderRequest).
