### ISSUE TITLE
Fork guide

### ISSUE THREAD

**Issue by diegoaguilar** [ubilabs/react-geosuggest#116]
I need to fork this repo in order to replace the component fields for material-ui own components, I will also include a map below. I KNOW this is not the scope of the component but I will use both a lot in my project and decided to fork and edit.

However, I'm quite confused on what steps I should follow to _edit & use_, (I won't do server rendering). I've seen npm scripts but I'm not totally sure which ones I should run in order to build and publish to my own npm module.

Thanks in advance

**Comment by ro-ka** [comment]
There is a part in the Readme, [that explains what to run](https://github.com/ubilabs/react-geosuggest#contributing). For publishing on npm it’s the default `npm publish`. You have to choose a new name in the `package.json` first, though.

You can style the component in Material style and you can add a map beneath without problems – the map doesn’t have to be in the component. Just create a new component, containing the map and the Geosuggest and you’re done. So, why fork?

**Comment by ro-ka** [comment]
No feedback, closing this.
