### ISSUE TITLE
Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by justincatalana** [ubilabs/react-geosuggest#120]
Trying this out with react-rails, just using the javascript file and not NPM, is anyone using this setup?

I get this error when just trying to render the plain component with no props specified. 

Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by brodeuralexis** [comment]
Yes, in version 1.20.0, a breaking change was introduced and ES5 support seems to have been dropped.  According to the lines in [this diff](https://github.com/ubilabs/react-geosuggest/commit/dbb5e35125fdf52eb22e9055d88510cdc9fe4687#diff-14d7874c67d31b1ba6483ba21d8f9d12L496),  the component is now only exported in a ES6 way.

You now have to do either of those
```js
const Geosuggest = require('react-geosuggest').default
import Geosuggest from 'react-geosuggest';
```

**Comment by justincatalana** [comment]
Thanks for the quick response, with the rails asset pipeline I'm requiring Geosuggest with the //=require directive

My code
`//= require react-geosuggest`

I'm still getting the error above.

**Comment by ro-ka** [comment]
I suppose that’s related to the way Babel handles the imports. There were some issues already with oldschool require not working anymore. Can you switch to a suggested method mentioned by @brodeuralexis above? I’m not firm with the Rails asset pipeline.

And thanks @brodeuralexis for responding so fast. :)

**Comment by ro-ka** [comment]
Any progress on this?

**Comment by ro-ka** [comment]
Closing this as there is no feedback.
