### ISSUE TITLE
How to focus input on mount

### ISSUE THREAD

**Issue by msalsas** [ubilabs/react-geosuggest#122]
I'm trying to use `focus()` to focus the input when the element is mounted, but I'm not sure of how to do it. I've tried to:

    import Geosuggest from 'react-geosuggest';
    ...

    componentDidMount() {
        Geosuggest.focus();
    }

but it's not the same rendered element, so doesn't work. Also tried adding `focus` as an option to the component, but neither is the way.
Maybe this method can only be used inside the callback functions.
Any light to this will be welcome. Thanks

**Comment by ro-ka** [comment]
You have to call on the reference of the rendered element:

```jsx
componentDidMount() {
    this.refs.geosuggest.focus();
}

render () {
  return <Geosuggest ref='geosuggest' />;
}
```

**Comment by msalsas** [comment]
Great! Thanks
