### ISSUE TITLE
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

### ISSUE THREAD

**Issue by BesatZardosht** [ubilabs/react-geosuggest#123]
I have generated the API key and added the script to my html head
I have installed react-geosuggest using this:
` npm install react-geosuggest --save 
`
I imported the component:

`const Geosuggest = require('react-geosuggest');
`
used it:
`<Geosuggest />
`
but I get this error:
`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).`

**Comment by ro-ka** [comment]
Did you resolve this? Had an issue with Babel that threw this error. The solution was to use ES6 `import`.

**Comment by BesatZardosht** [comment]
Yes, I solved it using this:

`import Geosuggest from 'react-geosuggest';`

**Comment by mcrider** [comment]
I'm using es5 and had to do `var Geosuggest = require('react-geosuggest').default;` to prevent this error.
