### ISSUE TITLE
Unit for radius?

### ISSUE THREAD

**Issue by lindskogen** [ubilabs/react-geosuggest#124]
What is the unit for radius?

**Comment by ro-ka** [comment]
This is the `radius` used for the Google Request ([AutocompletionRequest](https://developers.google.com/maps/documentation/javascript/reference?csw=1#AutocompletionRequest)):

> The radius of the area used for prediction biasing. The radius is specified in meters, and must always be accompanied by a location property. Alternatively, bounds can be used.

**Comment by lindskogen** [comment]
Can we update the readme with this information?

**Comment by ro-ka** [comment]
Can do. You like to open a PR?
