### ISSUE TITLE
Executing custom logic before API Request

### ISSUE THREAD

**Issue by mortargrind** [ubilabs/react-geosuggest#126]
Hi,

It would be really nice to have a callback before sending the request to the API to enable custom manipulation of user entered string.

Proposed API for this functionality:

```
function inputFilter(userInput){
    return manipulatedUserInput:
}
```

Use case for this:
As far as i know, Google AutoComplete API does not support limiting search results to a specific place other than country (like only displaying places from "London"). Only biasing the result list is possible (which is not same as limiting, you're still seeing the result from other places you don't care or want). To achieve a some sort of (hackish) limiting according to city for example, you can append and send city name along with the actual query. Let's say as a user i'm typing "Queen Street" and, the actual query sent to the API is "Queen Street London". So most probably i'll be seeing Queen Streets that are near London only :) (user will still be seeing "Queen Street" on the input field of course, that's the point)

Or, we can have a more generic callback called "beforeRequest" to execute any logic before making an API call. Something like:

```
function beforeRequest(request, componentInstance){
   
} 
```
It can even return false to prevent making any API call too.

If you're okay with either of these, we can decide the API and i can send you a PR?

**Comment by ro-ka** [comment]
I totally understand your use case, but we try to keep the API somehow minimal and not add hooks for everything. There is the bias of locations to a specific country, so I don’t see great value in this hook.
