### ISSUE TITLE
Option to Reduce Autocomplete API Requests

### ISSUE THREAD

**Issue by aflesher-change** [ubilabs/react-geosuggest#131]
Hi,

First off, great React component, exactly what we were looking for. My only issue that we are a little concerned with how many requests we'll be making to Google Autocomplete service, especially since we are expecting a lot of traffic to our site in the short term.

The most obvious solution I came up with was adding an option to only make a request to the API when there is a delay in between keystrokes.

https://github.com/aflesher-change/react-geosuggest/commit/508086679bc7da99a6df47c8c84e75532e2edfaf

If you like the solution I'll submit a pull request.

-- Adam

**Comment by ro-ka** [comment]
Thanks for bringing this up! May I ask what delay you are using? I try to keep the API minimal and functional (as every third issue wants to add another prop). So maybe we should add a small delay in general, without configuration?

**Comment by lsanwick** [comment]
I've added a a PR for this feature, as it's necessary to get the component to be functional at all in IE11.  There are still some serious perf problems in IE11 that I'm trying to determine the root cause of, but my guess is the JS engine there is just super slow, which is revealing the issues.

**Comment by ro-ka** [comment]
Just released in version `1.24.0`.
