### ISSUE TITLE
Is it possible to implement parameter TYPES with all of google accepted values?

### ISSUE THREAD

**Issue by dmxride** [ubilabs/react-geosuggest#132]

**Comment by ro-ka** [comment]
There is a `types` option which passes it’s values directly to the [AutocompletionRequest](https://developers.google.com/maps/documentation/javascript/reference#AutocompletionRequest). The documentation states the following for the allowed values:
> Four types are supported: 'establishment' for businesses, 'geocode' for addresses, '(regions)' for administrative regions and '(cities)' for localities. If nothing is specified, all types are returned.
