### ISSUE TITLE
Allow disabling of input autcomplete from browser

### ISSUE THREAD

**Issue by rewop** [ubilabs/react-geosuggest#136]
When I use react-geosuggest on my browser, I get the automatic autosuggestion from the browser on top of the google suggestions box. 

I would like to be able to use the attribute `autocomplete="off"` in the input field [to disable the browser autocomplete](http://www.w3schools.com/tags/att_input_autocomplete.asp), and increase usability.

However I see from the code, that it is not possible to pass down properties to the input field.

**Comment by ro-ka** [comment]
Just released in version `1.24.0`.
