### ISSUE TITLE
Pass in input value to onBlur callback

### ISSUE THREAD

**Issue by mendozao** [ubilabs/react-geosuggest#138]
I think it would be helpful to pass in the value of the input to the onBlur callback - just as you do with onChange

**Comment by ro-ka** [comment]
Thanks for the suggestion!

**Comment by frankmariette** [comment]
Have these changes been published to NPM yet?

**Comment by Caerostris** [comment]
Not yet. There will be a new release soon.

**Comment by ro-ka** [comment]
Just released in version `1.24.0`.
