### ISSUE TITLE
How to make suggestions in a Bootstrap drop-down style?

### ISSUE THREAD

**Issue by jwamsterdam** [ubilabs/react-geosuggest#139]
Currently, bootstrap offers the following class:

    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <li><a href="#">Action</a></li>

http://getbootstrap.com/components/#dropdowns

How can I add the dropdown-menu to the suggestions, so that my suggestions look like the bootstrap dropdown layout? Or is there any other solution?

Thank you!

**Comment by jwamsterdam** [comment]
I currently did it by custom css.

**Comment by ro-ka** [comment]
Currently it’s only possible to use custom CSS.

**Comment by ro-ka** [comment]
We do not plan on adding this atm.

**Comment by sandervanhooft** [comment]
> I currently did it by custom css.

@jwamsterdam Do you have example code for this?
