### ISSUE TITLE
hideSuggests not working out of the box

### ISSUE THREAD

**Issue by jwamsterdam** [ubilabs/react-geosuggest#140]
Hi, I have the following code:

    <Geosuggest inputClassName="form-control" initialValue={this.state.origin} onChange={this.handleFormChangeOriginNew} onSuggestSelect={this.handleFormChangeOriginSuggest}/>

with the following functions:

    handleFormChangeOriginNew(value) {
        this.setState({
            origin: value
        });
    }

    handleFormChangeOriginSuggest(suggest){
        this.setState({
            origin: suggest.label
        });
    }

But the suggestion menu is not automatically hidden when I click on it. Am I doing something wrong here?

**Comment by gkaemmer** [comment]
Are you including all the CSS? I was just having the same problem, and copying the structural styles from `src/geosuggest.css` fixed the issue, as the suggestions are only hidden with `max-height: 0`.

**Comment by jwamsterdam** [comment]
yes, that works! great! The docs should be updated though..

**Comment by ro-ka** [comment]
What would you like to have added to the docs?
