### ISSUE TITLE
Out of Box: Unexpected token <

### ISSUE THREAD

**Issue by Targun** [ubilabs/react-geosuggest#15]
Tried this out of the box, and got this error:

node_modules/react-geosuggest/src/Geosuggest.jsx Line 222: Unexpected token <

I'm sure it's something with complaining on my end.  Any suggestions?

**Comment by ro-ka** [comment]
This is linked to issue #11. Will update the build process to make the JSX transform before publishing to npm.

**Comment by Targun** [comment]
Thank you, looking forward to using your component.

**Comment by ro-ka** [comment]
Fixed and released as `1.4.0`.
