### ISSUE TITLE
support for more that one country

### ISSUE THREAD

**Issue by BesatZardosht** [ubilabs/react-geosuggest#164]
Thanks for the great project.
I was wondering if it supports restricting the results to more than one country. for example I would like to search addresses for Canada and USA.

**Comment by ro-ka** [comment]
Thanks for the kind words! :)

The `country` is a property set for the Google API, see the [reference](https://developers.google.com/maps/documentation/javascript/reference?csw=1#ComponentRestrictions). We cannot change the Google API.
