### ISSUE TITLE
Example of style prop

### ISSUE THREAD

**Issue by abeaclark** [ubilabs/react-geosuggest#166]
**I really like that you can set style for the elements within the component.**

Unfortunately, I have not been able to get it to work. Would anyone be willing to add an example to the docs or to the example that shows how this is to be done? I see brief section in the docs now, but it hasn't been working when I have tried that method. A more thorough example, perhaps incorporating the example styling would be great. 

Thanks for this great component!

**Comment by ro-ka** [comment]
Are you using the npm installed version? The style feature is in the current master branch but not yet released. We are close to a release, though.

**Comment by abeaclark** [comment]
@ro-ka Got it. That was exactly the problem. I should have noticed that, thanks for the headsup!

All good now. Thanks again for this component.

**Comment by ro-ka** [comment]
Perfect, we’ll release very soon.

**Comment by ro-ka** [comment]
Just released in version `1.24.0`.
