### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by lPadier** [ubilabs/react-geosuggest#17]
What are your thoughts on exposing focus state, and a method to clear the input state ?
This would allow the page UI to depend on suggest being open or not, and also allow a google maps like clear button

**Comment by ro-ka** [comment]
You mean like an `onFocus` callback method? What callbacks could be possible / helpful?

**Comment by lPadier** [comment]
yes, `onFocus` and `onBlur` callbacks, and maybe a `clear` callback so that the textfield can be emptied

**Comment by ro-ka** [comment]
Thanks for the PRs! Released as `1.5.0`.

And sorry for the late response / merge, just got back from holidays.  :)
