### ISSUE TITLE
Loading state

### ISSUE THREAD

**Issue by andrewBalekha** [ubilabs/react-geosuggest#174]
### Short description

When internet connection is to slow, there is a big gap between user enters value and showed result.

### Expected results

I expected to see some loading ticker while request is in progress, so user will know that something is happening.

### Actual results

User doesn't see if loading is in progress

**Comment by andrewBalekha** [comment]
I could do it, if it's not in backlog..

**Comment by Caerostris** [comment]
This could be implemented in two ways: Either by adding a CSS class to the input while loading, or by adding two events two the properties which fire when the Google API request starts, and when the Google API request finished.
Either way would allow the developer to implement their own loading spinner.

**Comment by andrewBalekha** [comment]
i think css classname would be enough... you can use pseudo selector to create a loading spinner.

**Comment by ro-ka** [comment]
Nice idea! I vote for a class, too. Feel free to implement!  😃

**Comment by ro-ka** [comment]
Added with #175
