### ISSUE TITLE
Input Blur before outstanding request returns

### ISSUE THREAD

**Issue by rodrigo-castillo** [ubilabs/react-geosuggest#179]
Quickly type in an address into the Geosuggest input, and tab out of the input before it has come back with suggestions. When the suggestions return, the geosuggest__suggests--hidden class is no longer applied to the suggestions and subsequent action on the page will not hide them until you activate the blur event on the input again.

On blur, any outstanding requests should be canceled and suggestions should not be shown.

**Comment by narendrashetty** [comment]
We need the close this issue @ro-ka

**Comment by yfr** [comment]
Yes. Thanks.
