### ISSUE TITLE
initialValue and server-side rendering

### ISSUE THREAD

**Issue by mmahalwy** [ubilabs/react-geosuggest#181]
initialValue only works on the client side, but on server-side rendering does not add value to the input. See:

```
warning.js:44Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) , hotel ..." value="Mission District, Sa
 (server) , hotel ..." value="" data-reactid="39">
```

**Comment by ro-ka** [comment]
Do you have an example setup for your used server side rendering?

**Comment by mmahalwy** [comment]
Got it working! Thank you

**Comment by ro-ka** [comment]
Great! Mind to explain the problem and solution in case someone else encounters the same problem?

**Comment by mmahalwy** [comment]
It was a problem with redux-form not playing nicely, so not specific to this library although I thought it was.

**Comment by ro-ka** [comment]
Ah, okay. Thanks! Happy that it works. 😄
