### ISSUE TITLE
default input events support

### ISSUE THREAD

**Issue by antoniopuero** [ubilabs/react-geosuggest#182]
I was trying to add key down event handler. You've said that other standard properties for input[type="text"] are allowed and propagated but it doesn't  seem to be so. 

onKeyDown={(e) => console.log(e)} //never gets triggered

**Comment by Caerostris** [comment]
The documentation gives a [link with a list of supported attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), and `onClick` is not amongst them.
However, I don't see a reason why we shouldn't support some events, such as `onClick`, `onMouseMove`, etc.
It would essentially be a matter of adding a few lines to `filter-input-attributes.js`.

**Comment by antoniopuero** [comment]
Hm, a keyDown event has nothing in common with the onClick event (except they are events). keyboard events are relevant to any input field so I'm a bit disappointed that you didn't include it to the allowed properties.

**Comment by ro-ka** [comment]
The `onKeyDown` event is already in use for handling the keyboard navigation on the component. Adding it to the allowed attributes would mean that this get’s overwritten which is not desired.

**Comment by antoniopuero** [comment]
@ro-ka hm, but you could call it as a callback after your inner handler is called. Or you could add a onKeyPress event support instead (not instead actually, but at least)

**Comment by ro-ka** [comment]
Will take a look next week.

**Comment by jt75** [comment]
+1 on @antoniopuero's comment.  I'd like to get a keypress event so I can take an action on the hosting div (basically hide the div when the user hits esc - right now my users have to click, and that's not as efficient).

**Comment by ro-ka** [comment]
You’re free to create a PR for this.

**Comment by antoniopuero** [comment]
Fixed in https://github.com/ubilabs/react-geosuggest/pull/213
