### ISSUE TITLE
Keyboard Enter should submit form

### ISSUE THREAD

**Issue by TaeKimJR** [ubilabs/react-geosuggest#184]
### Short description
When using the Geosuggest in a form, I would like the Geosuggest to allow me to submit the form when the Enter Keyboard button is pressed. This should act as any other input.

*onKeyDown, onKeyPress did not work.

### Expected results
I expected that by pressing the Enter key, the surrounding form should be submitted.

### Actual results
Instead of the form not being submitted, nothing happens.

### Additional Information
I am trying to allow the User to either select a suggestion, or type in any text they would like (suggestions are not required).

**Comment by Caerostris** [comment]
It could actually be that we just implemented this in #183.
I'll check verify this later today.
#183 is not on NPM yet. It'll be part of the next minor release which should be published some time during the next week.

**Comment by Caerostris** [comment]
First of all, I added everything but key events to #183. I'll open a new PR for `onKeyPress` etc.
Unfortunately, simply adding `onKeyPress` to `filter-input-attributes.js` won't be enough for your use case. The problem is here: https://github.com/ubilabs/react-geosuggest/blob/master/src/input.jsx#L59
@ro-ka Is the prevent default necessary?

**Comment by ro-ka** [comment]
It is there to prevent submitting a form while selecting a suggest. Would be irritating when both happens.

**Comment by Caerostris** [comment]
Indeed. So if we are to resolve this issue we will have to check whether or not the suggest list is being displayed. If so, prevent the default and select a suggest. If not, ignore the event.

**Comment by ro-ka** [comment]
That sounds like a plan.  :)

**Comment by ro-ka** [comment]
Anyone wants to implement this?
