### ISSUE TITLE
Is it possible to force delivery address in response ?

### ISSUE THREAD

**Issue by franckmaurin** [ubilabs/react-geosuggest#186]
Hello,

I want to use react-geosuggest for an e-commerce web app but I need to get real delivery addresses (and not items like "New York, New York State, US".

Do you have a great way to do this ? Thanks

**Comment by Caerostris** [comment]
Have you tried using the `types` property?

**Comment by franckmaurin** [comment]
@Caerostris Yep, but the "geocode" value contains also items like "New York, New York State, US".

**Comment by dimafeldman** [comment]
Hey @franckmaurin look at this link: https://developers.google.com/maps/documentation/geocoding/intro

the selected suggest object contains "formatted_address" key that looks like this: "1600 Amphitheatre Parkway, Mountain View, CA 94043, USA"

**Comment by Caerostris** [comment]
https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingAddressTypes
Try `street_address` 👍

**Comment by franckmaurin** [comment]
@dimafeldman @Caerostris thanks guys ! 

I noticed the "street_address" value that match with my need but what is the component property for specifying the "Address Component Types" ? Because if it is not provided, I can create it and make a PR :)

**Comment by Caerostris** [comment]
@franckmaurin My bad, I got the request and result documentations mixed up. There is no `street_address` type for requests. In that case I think your only option is something along these lines:
```js
<Geosuggest
  types={['geocode']}
  skipSuggest={function(suggest) {
    return !(suggest.types && suggest.types.includes('street_address'));
  }} />```
The results are quite terrible though, as Google won't return a `street_address` precision result until you type the full street name and a house number.

**Comment by franckmaurin** [comment]
Thanks you @Caerostris, this way rocks !

**Comment by Caerostris** [comment]
Great, you're welcome 😀
