### ISSUE TITLE
Arrow keys don't work

### ISSUE THREAD

**Issue by cookkkie** [ubilabs/react-geosuggest#187]
### Short description

I was trying to use the arrow keys to navigate between the suggests

### Expected results

I expected it to work the same way it does in the provided exemple.

### Actual results

It doesn't work at all.

Thanks.

**Comment by Caerostris** [comment]
Could you please provide the code snippet you used to initialise Geosuggest?
Do any errors show up in the javascript console?

**Comment by cookkkie** [comment]
Yes, sorry @Caerostris 

```
import React, { Component } from 'react';
import Geosuggest from 'react-geosuggest';

class AddressInput extends Component {

  constructor(props) {
	super(props);
  }

  handleChange = (value) => {
	this.props.onChange({address: value, seleted: false});
  }

  handleSuggestSelect = (suggest) => {
	this.props.onChange({address: suggest.label, selected: true});
  }

  render() {
	const {value, onChange, id, placeholder, ...rest} = this.props;
	return (
	  <Geosuggest
		{...rest}
		ref="input"
		queryDelay={0}
		onSuggestSelect={this.handleSuggestSelect}
		onChange={this.handleChange}
		country="fr"
		initialValue={value.address || ""}
		id={id}
		placeholder={placeholder}/>
	);
  }
}
```
And even when I replace the render function by
```
render() {
    return <Geosuggest />;
}
```
The bug is still there. And no error in the console. Even when hitting the arrow keys.

**Comment by Caerostris** [comment]
I think the solution is very simple. Have you added CSS styling to the `.geosuggest-item--active` class?
I suspect that the arrow keys do work in your case. You have to add proper styling or else you won't be able to see which suggest is currently selected.

**Comment by cookkkie** [comment]
Thank you very much. That was it.

**Comment by Caerostris** [comment]
Perfect 👍 You're welcome!

**Comment by Saifadin** [comment]
For whoever comes across this. The current classname is: `.geosuggest__item--active`
