### ISSUE TITLE
Trigger selection through button press?

### ISSUE THREAD

**Issue by finaiized** [ubilabs/react-geosuggest#188]
I'm wondering if it's possible to "select" the suggestion (ie. triggering `onSuggestSelect`) by clicking a button. I've activated `autoActivateFirstSuggest` so a place (should one exist) is always exists. I would like to press a "next" button, possibly while the suggestions are still up, and "select" it. I guess alternatively, if I could fetch the list of suggestions provided in the suggestions list, I could do it programatically as well.

**Comment by ro-ka** [comment]
Why not just click the event in the list?

**Comment by finaiized** [comment]
Sure, but I'd like to have a "Go to" button so to speak that the user can click to auto-select the suggestion. (That's on top of hitting enter and clicking the event).

**Comment by ro-ka** [comment]
We could add a `.selectActiveSuggest()` handler that is available like `.clear()` and so on. Anyone want’s to implement this?

**Comment by finaiized** [comment]
I've played around with implementing this, and found the main issue is that clicking a button causes `onBlur` to fire, resetting the `state.activeSuggest`. For my purposes, not resetting `state.activeSuggest` works for me, but I'm not sure if it'll cause some unintended side-effects. Thoughts?

**Comment by mmahalwy** [comment]
Any update on this?

**Comment by ro-ka** [comment]
Closing this as this is very old. If still an issue or someone wants to take this, reopen.
