### ISSUE TITLE
Opening Hours?

### ISSUE THREAD

**Issue by husek** [ubilabs/react-geosuggest#189]
There's a way to get the Opening hours object using this lib?

**Comment by ro-ka** [comment]
The `suggest.gmaps` object contains the complete response from Google. As this library uses the  [`googleMaps.places.AutocompleteService`](https://developers.google.com/maps/documentation/javascript/reference#AutocompleteService), there are no opening hours. You can use the `place_id` returned from Google and query for the opening hours at the Places API.
