### ISSUE TITLE
onSuggestSelect is not fired when geocoding is unsuccessful

### ISSUE THREAD

**Issue by ondy1985** [ubilabs/react-geosuggest#193]
When you select some location that has no gps coordinates associated with it (why that happens beats me) from the suggestions, neither _onSuggestSelect_ nor _onChange_ callbacks are fired. 

This is because if the suggest does not have a location property, the Geosuggest tries to geocode it and if the geocode fails, it just does nothing and only fires the onSuggestSelect if the location is found.

I would expect it to either fire the onSuggestSelect callback anyway or at least calling the onChange callback, so I know that the user input has changed.

**How to reproduce**

1. Go to http://ubilabs.github.io/react-geosuggest/
2. Open the console
3. Type "**1294 U.S. 1**" into the input 
4. Check the console - it says "input changes to :1294 U.S. 1"
5. Choose the "**1294 U.S. 1, ME, United States**" from the suggestions
6. Check the console again - it says nothing - input was not changed according to the console, which is wrong, because the input was "1294 U.S. 1" and now it is "1294 U.S. 1, ME, United States" and no suggestion was selected either...

**Comment by ro-ka** [comment]
Thanks for reporting!

**Comment by dimafeldman** [comment]
Hey, any progress with this one? I'm facing the same issue

**Comment by maxkudla** [comment]
I don't know what exactly geocodeSuggest does, but next fix works for me...

**{ address: suggest.label }**

      value: function geocodeSuggest(suggest) {
          var _this4 = this;

          this.geocoder.geocode({ address: suggest.label }, function (results, status) {
            if (status !== _this4.googleMaps.GeocoderStatus.OK) {
             // just return what we have
              _this4.props.onSuggestSelect(suggest);
            }

            var gmaps = results[0],
                location = gmaps.geometry.location;

            suggest.gmaps = gmaps;
            suggest.location = {
              lat: location.lat(),
              lng: location.lng()
            };

            _this4.props.onSuggestSelect(suggest);
          });
        }

**Comment by domhede** [comment]
Yeah seeing this issue as well.

**Comment by jordanmkoncz** [comment]
Ran into this issue today as well!
