### ISSUE TITLE
Remove suggestions dropdown with clear()

### ISSUE THREAD

**Issue by mattecapu** [ubilabs/react-geosuggest#194]
How can I "reset" the component by clearing the user input and the suggestions dropdown?
`clear()` resets just the textbox but the suggestions remain visible.

**Comment by ro-ka** [comment]
The suggest list should be cleared, too. Thanks for reporting! Anyone wants to implement this?

**Comment by narendrashetty** [comment]
@ro-ka I just tested the `clear()` method. It resets the textbox and also clears suggestion dropdown. @mattecapu can you please list the steps to reproduce.

**Comment by ro-ka** [comment]
Closing as there is no new feedback. Reopen if it occurs again with steps to reproduce.

**Comment by romancieslik** [comment]
I guess you're talking about 2 different things:

1. completely close the suggestion dropdown 
2. clear the contents of the suggestion but leaves it open
