### ISSUE TITLE
Some options don't return suggestion

### ISSUE THREAD

**Issue by mrjrdnthms** [ubilabs/react-geosuggest#196]
### Short description

I search for "National Wine Centre, Adelaide". I select the first result. No onSuggestion event fires because the geocoder returns no results

### Expected results

I expected that if an option appears in the dropdown it should be returned by geocoder

### Actual results

No result is returned

### Reproduction steps

1. Go to 'http://ubilabs.github.io/react-geosuggest/'
2. Type 'National Wine Centre, Adelaide'
3. Select first option
4. Notice no suggestion is returned from geocoder

**Comment by jordanmkoncz** [comment]
I believe this is a duplicate of https://github.com/ubilabs/react-geosuggest/issues/193.

**Comment by mrjrdnthms** [comment]
I don't think its the same. Might be wrong but I think in #193 the issues is some geocoder results don't include a location. In this one (#196) the issue is some results are returned by the first api call that aren't found by the second geocode call.

**Comment by ro-ka** [comment]
Just tested as described but there is a suggest returned for me… 

<img width="457" alt="bildschirmfoto 2016-09-23 um 12 52 21" src="https://cloud.githubusercontent.com/assets/840022/18783549/9cdc1058-818c-11e6-9f75-8ad937359238.png">

Anything else to reproduce this?

**Comment by mrjrdnthms** [comment]
No additional steps to reproduce. It looks like it is working now. I may have missed something or its possible google updated the api. Either way looks good now so closing. thanks
