### ISSUE TITLE
Support adding class names to suggests and suggest items

### ISSUE THREAD

**Issue by edudavid** [ubilabs/react-geosuggest#197]
Is possible to set className for suggests and suggest items just as we set for inputClassName props?

This is my code

```
import React from 'react'
import classes from './LocationInputComponent.scss'
import Geosuggest from 'react-geosuggest';

export const LocationInputComponent = () => (
  <div>
    <Geosuggest
      inputClassName={ classes.geosuggest } />
  </div>
)
```

In the LocationInputComponent.scss file, I have exactly the same classes as [https://github.com/ubilabs/react-geosuggest/blob/master/src/geosuggest.css] 

The result of `classes.geosuggest` is something like this:  `geosuggest__input LocationInputComponent__geosuggest___91ULR`

I would like to be able to do something like this:

```
import React from 'react'
import classes from './LocationInputComponent.scss'
import Geosuggest from 'react-geosuggest';

export const LocationInputComponent = () => (
  <div>
    <Geosuggest
      inputClassName={ classes.geosuggest }
      suggestsClassName={ classes.geosuggest__suggests }
      suggestItemClassName={ classes.geosuggest__suggest__item } />
  </div>
)
```

I believe, this is the same (or almost the same) issue as: [https://github.com/ubilabs/react-geosuggest/issues/62]

**Comment by edudavid** [comment]
Hi, I found a solution for this issue: If you add :gobal{ } around the classes you want to use in the component, webpack will keep the original classNames.

Anyway I am submitting a pull request with this update:

Adding props suggestsClassName and suggestItemsClassName 
[https://github.com/ubilabs/react-geosuggest/pull/198]

**Comment by ro-ka** [comment]
As written in #198: 
> A feature could be to adjust the passed in className to create an own namespace. E.g. Passing in className='my-own' adds my-own__suggests to the list.

What do you think?

**Comment by oleblaesing** [comment]
I'm using Bootstrap for my component styling and I'm missing a feature of this kind! Applying **additional** classes to the suggestion items would be the simplest solution for me (and I guess for others too). Is it possible to reopen the PR if I extend the classes via properties instead of overwrite them? Or should I open a complete fresh one?

**Comment by ro-ka** [comment]
Feel free to open a PR that is in line with [`suggestsHiddenClassName`](https://github.com/ubilabs/react-geosuggest#suggestshiddenclassname). See #224 on how to implement.
