### ISSUE TITLE
Support for labels

### ISSUE THREAD

**Issue by SergeyKhval** [ubilabs/react-geosuggest#199]
As [Webaim.org](http://webaim.org/techniques/forms/#labels) suggests all text inputs should be properly labeled. 

Something like this might be good:

```xml
<Geosuggest label="Label text" />
```

which results in:

```html
<div class="geosuggest">
  <div class="geosuggest__input-wrapper">
    <label for="geosuggest-id" class="geosuggest__label">Label text</>
    <input type="text" id="geosuggest-id" class="geosuggest__input" value="">
  </div>
</div>
```

**Comment by ro-ka** [comment]
That sounds good! Can you create a PR? I would suggest that the label is only created when there is a label text passed in. Else it is without a label just like it is now.
