### ISSUE TITLE
Access Places Data

### ISSUE THREAD

**Issue by AdamBrodzinski** [ubilabs/react-geosuggest#2]
It's not clear from the Readme or Example.... does this return the Places API data (street_address, country, administrative_area_level_1, etc...) ?

For example i'm currently using a jQuery GeoComplete that returns [these fields](https://github.com/ubilabs/geocomplete#address-and-places-specific-component-types) in the response.

I'm not terribly familiar with the Google API's, would that data require extra calls or does it just need to be exposed?

Thanks!

**Comment by ro-ka** [comment]
The results vary slightly, depending whether it is a predefined result or a Google Maps API result.

A predefined result looks like this:

```json
{
  "label": "Rio",
  "placeId": "Rio",
  "location": {
    "lat": -22.066452,
    "lng": -42.9232368
  }
}
```

A Google Maps result looks like this:

```json
{
  "label": "Rio de Janeiro, Brazil",
  "placeId": "ChIJw4riypQYmAAR0IMFwRrDSQM",
  "location": {
    "lat": -22.9068467,
    "lng": -43.17289649999998
  }
}
```

So the only difference is the `placeID`. It is either the predefined one or the Google Maps one. Would you prefer to get the complete Google Maps result just like in the geocomplete plugin (which is by us, too ;) )? Also, not sure how to handle the `placeId`. Return as null when not a Google Maps result?

You can check the results by opening the console and selecting results.

**Comment by AdamBrodzinski** [comment]
Ahhh, that makes a lot of sense now! I didn't realize the geocomplete and places API's were separate.
From the readme I thought it was supposed to fetch the places data to, not just the long/lat.

If I used this repo and had the ID or Long/Lat, would i then make an additional call to Google Places to get the full street_address, country, administrative_area_level_1, etc...data?

Basically i'm dropping my old templating language for React and the last thing stopping me is to replace the GeoComplete so that I can search for an address, click it, and autofill some form fields as needed. (Actually using Geocomplete after React's render may work out of the box since I still have jQuery.. haven't tried yet).

**Comment by ro-ka** [comment]
Just checked. First there is the autocomplete request to the places API. That returns something like this:

```json
[
  {
    "description":"NYC, NY, United States",
    "id":"7eae6a016a9c6f58e2044573fb8f14227b6e1f96",
    "matched_substrings":[
      {"length":3, "offset":0}
    ],
    "place_id":"ChIJOwg_06VPwokRYv534QaPC8g",
    "reference":"CmRYAAAAmsOZZgKoe5We5NX8Wfi0mzv9F3n2FqRMxMlOyna0dFW_QYXRI5u8gymVeR6xE8dfAmmUI3eDitA590MQs7G26Nl4z2NdA3amkdxL4UjgE-Sfms0wYXNbb_AdP9gMpCmlEhD4NqvTIcFJp27tAfvMCCzQGhTJ7dbZPhDw9ZvR4gaVEYpNzmPJYA",
    "terms":[
      {"offset":0, "value":"NYC"},
      {"offset":5, "value":"NY"},
      {"offset":9, "value":"United States"}
    ],
    "types":[
      "locality",
      "political",
      "geocode"
    ]
  },
  …
]
```

As there is no location data in that response, when selecting a suggestion later, there is a geocoding request. That geocoding request returns all the information you mentioned. Currently it gets filtered and only the location is returned.

I could add all the other data, too. Would keep the `.location`, too for not breaking. The complete Google Geocoding response data could be added at `.geo`. It would only be present when a geocoding was necessary. For presets this won’t apply when initialized with a location. What do you think?

**Comment by ro-ka** [comment]
Complete places data is now available and documented: https://github.com/ubilabs/react-geosuggest#onsuggestselect

Thanks for reporting! Hope this helps in converting your app.

**Comment by ro-ka** [comment]
P.S.: Released as `1.2.0`.

**Comment by AdamBrodzinski** [comment]
Hey thanks @ro-ka !! :beers: 

Keeping the location is ideal too since I can save that data to Mongo and use their Geospatial query when needed!

![giphy](https://cloud.githubusercontent.com/assets/1445367/7971284/96f3e772-0a11-11e5-8f9c-6193d440105e.gif)

**Comment by ro-ka** [comment]
Great to hear!  :smile:
