### ISSUE TITLE
Ability to pass on any options supported by Google API

### ISSUE THREAD

**Issue by owais** [ubilabs/react-geosuggest#20]
Would be nice if we could pass on any options (Country for example) available here https://developers.google.com/maps/documentation/javascript/places-autocomplete to the react component.

**Comment by ro-ka** [comment]
Thanks for the suggestion! Released as `1.6.0`.

And sorry for the long silence, I was on holidays. :)

**Comment by ro-ka** [comment]
(See the [Readme](https://github.com/ubilabs/react-geosuggest#country)) for how to use!
