### ISSUE TITLE
Clearing the suggestion

### ISSUE THREAD

**Issue by boriswexler** [ubilabs/react-geosuggest#201]
How do you handle the scenario where after selecting a suggest the user erases their entry (partially or totally)? Currently it keeps the last suggest as value, so the form will erroneously save the last selected suggestion even though the user has chosen to erase their input.

**Comment by ro-ka** [comment]
That’s true, there should be a trigger that nothing is selected when `onBlur` is triggered. Feel free to create a PR to handle this!

**Comment by shek8034** [comment]
We can listen to onInputChange() callback and remove the suggest when the input is changed. It means that user has to select location from dropdown all the time when he changes the input. Doable this way

**Comment by sandervanhooft** [comment]
@ro-ka @shek8034 

Any progress / example for this?

**Comment by sandervanhooft** [comment]
I'm currently doing it this way as a workaround (`onSearchLocationSelect(...)` and `clearSearchLocation()` are redux actions):

```
<Geosuggest
          onSuggestSelect={ (suggest) => onSearchLocationSelect(suggest) }
          onSuggestNoResults={ () => clearSearchLocation() }
          onChange={
            (value) => {
              if( !value || value === "" ) {
                clearSearchLocation()
              }
            }
          }
/>
```
