### ISSUE TITLE
Bad 'fixtures' in props might cause an error

### ISSUE THREAD

**Issue by amireldor** [ubilabs/react-geosuggest#202]
I'm not sure if this is a real issue but bear with me.

When working with fixtures, it came to that one of the fixtures which was provided to Geosuggest in my code was bad. The current fixtures code relies on a fixture to have a `label` and then it can `.match` against it.

Because my fixture object was funny, there was no `label`, and `.match` failed, giving a sad error on the console and no search suggestions were available. When pressing 'enter' however, the geo object _was_ loaded correctly, so my application did not fail completely.

This is the fixtures code I came across. `this.props.fixtures` is not fully validated so stuff might break.

```javascript
    ...
    this.props.fixtures.forEach(suggest => {
      if (fixturesSearched >= maxFixtures) {
        return;
      }

      if (!skipSuggest(suggest) && suggest.label.match(regex)) {
        fixturesSearched++;

        suggest.placeId = suggest.label;
        suggest.isFixture = true;
        suggests.push(suggest);
      }
    });
   ...
```

**Comment by ro-ka** [comment]
As the Readme says, there must be a label in the fixtures. If there is no label provided it wouldn’t make sense to have a fixture…

Closing this as it is not a real issue. But you’re free to open a PR if you’d like to have this handled somehow.
