### ISSUE TITLE
Warning: You are manually calling a React.PropTypes validation function

### ISSUE THREAD

**Issue by hdornier** [ubilabs/react-geosuggest#203]
### Short description

Hi, I've been trying to get Geosuggest working, but encounter 23 warnings of the following sort:

`app.js:53642 Warning: You are manually calling a React.PropTypes validation function for the `fixtures` prop on `Geosuggest`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`

Is this normal? I also get the following error upon first typing into the input box:
`Uncaught TypeError: Cannot read property 'value' of undefined`
Which I found was discussed in another issue, but was resolved by uninstalling and reinstalling.

Thought two may be related. I know that my google maps places script is properly inserted, and that geosuggest is being required correctly.

Any thoughts would be much appreciated!
Thanks,
Henry

**Comment by davidwadge** [comment]
Also experiencing this issue.

**Comment by ro-ka** [comment]
We are not calling the `PropTypes` directly anywhere. Tested the example with all updated npm.
