### ISSUE TITLE
Styling text in results

### ISSUE THREAD

**Issue by dvlasenko96** [ubilabs/react-geosuggest#204]
### Short description

I was trying to type something in the field and have suggestion.

### Expected results

I want to select with bold few first letter like on default google autocomplete. http://take.ms/OxTsp

### Actual results

Nothing happens

### Additional Information

```
http://take.ms/OxTsp
```

**Comment by kstratis** [comment]
@ro-ka Is it possible to get such functionality?

**Comment by ro-ka** [comment]
There is `[getSuggestLabel](https://github.com/ubilabs/react-geosuggest#getsuggestlabel)` which you can use to style the label whatever you like.

**Comment by dvlasenko96** [comment]
@ro-ka I wrote a function, that helps me with this question.
`
getSuggestLabel(suggest) {
		let description = suggest.description;
		let startTag = '<span>';
		let endTag = '</span>';
		let offsetTag = 0;

		suggest.matched_substrings.forEach(el => {
			description = description.splice(el.offset + offsetTag, 0, startTag);
			offsetTag += startTag.length;
			description = description.splice(el.offset + el.length + offsetTag, 0, endTag);
			offsetTag += endTag.length;
		});

		return description;
	}
`

But, I have faced with a problem, I can not show a correct item with HTML tags. http://take.ms/bgDOh

**Comment by nicolasthy** [comment]
@dvlasenko96 Did you manage to find a solution to your problem? Trying to achieve the same result but don't know how to avoid the "<span>" il the search results...

**Comment by ro-ka** [comment]
You are concatenating simple strings. Use JSX to render the description. Does this help?

**Comment by nicolasthy** [comment]
Perfect ! This worked for me:
```
getSuggestLabel(suggest) {
    return (
      <div>
        <div>{suggest.structured_formatting.main_text}</div>
        {suggest.structured_formatting.secondary_text}
      </div>
    );
  }
```

**Comment by cuth** [comment]
> However I'm getting an [object Object] when selecting a suggestion.

Same. Is there any way around this?
