### ISSUE TITLE
Suggestion list with selected remains after select (mobile)

### ISSUE THREAD

**Issue by cyk** [ubilabs/react-geosuggest#208]
### Short description

Using a mobile device, upon tapping a suggestion, all suggestions in the list clear except for selected.
### Expected results

I expected that the suggestion list would clear entirely after selecting a suggestion (i.e., how it behaves on the desktop).
### Actual results

The suggestion list continues to show the selected suggestion until it is selected again.
### Reproduction steps
1. Go to http://ubilabs.github.io/react-geosuggest/ (Android Chrome 53)
2. Tap into 'Search Places' input
3. Type the name of a place
4. Tap first suggestion
5. Suggestion list is reduced to selected suggestion
### Additional Information

<img src="https://cloud.githubusercontent.com/assets/423755/18804183/75ce1aea-81ac-11e6-94f0-032a96ab1fbc.gif" width="300" />

**Comment by Scarysize** [comment]
Can't reproduce this on my device (Moto G, Chrome 53).
What device are you using?

**Comment by cyk** [comment]
We've reproduce it on a Samsung Galaxy S5 and Moto X Pure Edition (2014).

**Comment by ro-ka** [comment]
Cannot reproduce neither (Moto X Play 2015).

**Comment by cyk** [comment]
Can no longer reproduce on Moto X Pure Edition (2014) with Chrome 55.

**Comment by ro-ka** [comment]
Will close it then. Thanks for reporting though!
