### ISSUE TITLE
Patch 1.25.0 -> 1.25.1 has breaking changes

### ISSUE THREAD

**Issue by levindixon** [ubilabs/react-geosuggest#209]
### Short description

Recent changes to dependencies in `1.25.1` caused a build to break.

### Expected results

A breaking change should bump the minor version.

### Actual results

Patch version was bumped.

**Comment by jeffkeeling** [comment]
you'll need to run `npm install --save react-addons-shallow-compare`

**Comment by yfr** [comment]
Updating shouldn't be a problem as the new peerDependencie should already be installed. For new installations, we have added a paragraph in the readme that you need to install peerDependencies. 

From our view, this is not a breaking change.

**Comment by levindixon** [comment]
But most deploys run a fresh `npm install` in which case the build will break.

**Comment by yfr** [comment]
Oh, I'm sorry. You are absolutely right. We did not think about this. To be honest this is the first time we have peer dependencies in our projects. 

How can we fix this?

**Comment by levindixon** [comment]
Not too sure about the peer dependency issue, I'd have to dig into it. For the semver issue, [this might help](http://semver.org/#what-if-i-inadvertently-alter-the-public-api-in-a-way-that-is-not-compliant-with-the-version-number-change-ie-the-code-incorrectly-introduces-a-major-breaking-change-in-a-patch-release).

**Comment by Scarysize** [comment]
Well, shouldn't a minor version bump do the trick?

**Comment by Scarysize** [comment]
@yfr This should be fixed with the v2.0 release?
