### ISSUE TITLE
tab isn't working

### ISSUE THREAD

**Issue by jbhatab** [ubilabs/react-geosuggest#210]
### Short description

I haven't disabled tabbing and it's just not working. It tabs through everything else on the page like normal but never the autosuggest.
### Expected results

tab to work
### Actual results

tab didn't work. Just worked like normal tabbing

**Comment by Scarysize** [comment]
We will discuss if this is a feature we want to add. It might screw with the `tabIndex` of the surrounding page.
@yfr what do you think?

**Comment by ro-ka** [comment]
It tabs correctly in the demo — Can you provide an example implementation?

**Comment by ro-ka** [comment]
Reopen with further information.
