### ISSUE TITLE
Support coords with N E 

### ISSUE THREAD

**Issue by themre** [ubilabs/react-geosuggest#211]
### Short description

When I'm trying to search with 40.8517N, 109.6289E, I don't get right result, whereas with 40.8517, 109.6289 the result is correct.

### Expected results

When I input 40.8517N, 109.6289E, I should be located here: https://www.google.si/maps/place/40%C2%B051'06.1%22N+109%C2%B037'44.0%22E/@40.8125954,108.8931254,8.46z/data=!4m5!3m4!1s0x0:0x0!8m2!3d40.8517!4d109.6289?hl=sl

### Actual results

Nothing happens.

### Reproduction steps
1. Enter 40.8517N, 109.6289E in text field
2. Hit ENTER

**Comment by Scarysize** [comment]
We are using the Google Maps "Place Autocomplete" Service to gather the results the component is displaying. The service takes in the **name** of a place and will **suggest** an actual location to you.
If you already have the _exact_ location you are looking for (latitude, longitude), why would you need a suggestion?

**Comment by themre** [comment]
no, I don't want a suggestion, only that it would set center based on 
the coords even if you have 50N, 10E as coords.
For example if you put in google 
https://www.google.com/maps/place/50°00'00.0"N+10°00'00.0"E/ or 
https://www.google.com/maps/place/50°00'00.0"+10°00'00.0"/ you get the 
same location, but with this component it doesn't do anything with 
coords containing N E.
