### ISSUE TITLE
Update Readme to specify all the allowed attributes for input

### ISSUE THREAD

**Issue by Shobhit1** [ubilabs/react-geosuggest#218]
### Short description

I was trying to do add maxLength to the geo suggest component, but I was not sure if it accepts it or not because there was no mention of it in the readme. Then, i went to the source code and checked it out that there is a list of attributes which are accepted for input fields.
### Expected results

It would be nice to have all the attributes listed out in readme.
### Actual results

There is no listing of the allowed attributes.

PS: This is actually not a bug, just an observation.

**Comment by yfr** [comment]
Nice finding. Feel free to open a PR. Would be cool to have the docs updated!

**Comment by Shobhit1** [comment]
Thanks @narendrashetty for the PR.
