### ISSUE TITLE
OnKeyPress not working

### ISSUE THREAD

**Issue by StrikoMirko** [ubilabs/react-geosuggest#219]
### Short description

I was trying to bind my own onKeyPress logic to the component through the onKeyPress prop but it does not work.
this is the prop on GeoSuggest component 
`onKeyPress={this.onKeyPress}`

My component constructor
`constructor(props) {
    super(props)

```
this.state = {
  lat: null,
  lng: null,
  placeId: null,
  searchedAddress: null
}

this.preformedSearch = false

this.onSuggestSelect = this.onSuggestSelect.bind(this)
this.getSelectedLocation = this.getSelectedLocation.bind(this)
this.onChange = this.onChange.bind(this)
this.onFocus = this.onFocus.bind(this)
this.onBlur = this.onBlur.bind(this)
this.getSuggestLabel = this.getSuggestLabel.bind(this)
this.onKeyPress = this.onKeyPress.bind(this)
```

  }`

And the function that is supposed to fire
`onKeyPress() {
    console.log('key press')
  }`

Can someone confirm if this should work?

Thank you.

**Comment by esauter5** [comment]
@StrikoMirko I'm seeing the same thing. Going to take a look at the source and see if I can find anything.

**Comment by esauter5** [comment]
@StrikoMirko You might be using an out-of-date version. I noticed I was using 1.22.0 which does not implement `onKeyPress`

**Comment by ro-ka** [comment]
Reopen if it occurs with the current version.
