### ISSUE TITLE
Supply Visible Class Names

### ISSUE THREAD

**Issue by arb** [ubilabs/react-geosuggest#223]
### Short description

My project uses CSS modules and don't have globally accessible class names like ".geosuggest__suggests--hidden" and ".geosuggest__item--active". Would it be possible to expose those names so they could be something else and fall back to the defaults if not supplied? I this something you would accept a PR for?

**Comment by yfr** [comment]
Hey, I would love to see a feature like this. Was running a similar problem with CSS modules but used just global class names. So feel free to open a PR and lets discuss there.

**Comment by eamonpenland** [comment]
I was having this issue too. solved with 

`:global(.geosuggest__suggests--hidden` {
  max-height: 0;
  overflow: hidden;
  border-width: 0;
})`

in style.css
