### ISSUE TITLE
Document Google APIs Used

### ISSUE THREAD

**Issue by arb** [ubilabs/react-geosuggest#226]
### Short description

It would be handy for people trying to purchase web api tokens from Google to know exactly what services this uses based on the supplied options.

**Comment by yfr** [comment]
We are just using the Geocoder from the standard maps API and the AutocompleteService with the additional places API.

So if you like you could open a PR for this or I will do that later next week.

Anyway, thanks for the question. I also think it's important to know.

**Comment by oyeanuj** [comment]
@yfr I've issued a PR (#243) based on your above comment. Please let me know if that is accurate.
