### ISSUE TITLE
Select Suggestion, all suggestions stay on screen

### ISSUE THREAD

**Issue by thedanotto** [ubilabs/react-geosuggest#227]
### Short description

I type in my input, it gives 5 suggestions, I click on a suggestion, it updates the input with the selected suggestion..... THE SUGGESTIONS STAY ON THE SCREEN.

![screen shot 2016-11-07 at 1 05 04 am](https://cloud.githubusercontent.com/assets/5581358/20049058/47c0bd22-a486-11e6-8288-bb177730c8ff.png)

### Expected results

I expected that by clicking on a suggestion the suggestions would disappear.

### Actual results

the suggestions sayed.

### Reproduction steps

1. Implement this code or something similar `<Geosuggest placeholder="Address, City or Zip" country="us" />`
2. Type into the input box
3. Click a suggestion.

I figure I need to use `onSuggestSelect` or `onActivateSuggest` but it is not clear how to utilize. Thanks

**Comment by ro-ka** [comment]
That’s unexpected, indeed. Is there an error in the console? Or can you provide a test setup (on Codepen or similar) so we can reproduce this? As the [example page](http://ubilabs.github.io/react-geosuggest/) demonstrates, it is working as expected.

**Comment by thedanotto** [comment]
@ro-ka I will look at reproducing on codepen. Where can I look at the source code for the example page?

**Comment by thedanotto** [comment]
DOY FIGURED IT OUT...

I never added
```
.geosuggest__suggests--hidden {
  display: none;
}
```

to my css

**Comment by ro-ka** [comment]
Great!  🎉
