### ISSUE TITLE
Not working in IE because of use of Array.prototype.find()

### ISSUE THREAD

**Issue by jlongbottom** [ubilabs/react-geosuggest#229]
### Short description

This does not work in IE because IE does not support Array.prototype.find(). As soon as the suggestion list appears, it throws an error and further suggestions fail to appear when the user continues to type.

### Expected results

It should continue providing suggestions when the user modifies their input.

### Actual results

No more suggestions are appearing.

### Reproduction steps

1. Start typing and observe list of suggestions.
2. Continue typing

### Additional Information

I was able to fix this with a polyfill in my app.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill

**Comment by HugoGiraudel** [comment]
Possible fix: bundle `lodash.find` (exclusively, not the whole lib).

**Comment by ro-ka** [comment]
As there are polyfills for this, the surrounding app can use that. It would be duplicated if we also include a polyfill in this component.
