### ISSUE TITLE
unexpected behavior from ignoreEnter

### ISSUE THREAD

**Issue by esauter5** [ubilabs/react-geosuggest#232]
### Short description

I'm not quite understanding the inverse relationship between `this.state.isSuggestsHidden` and `ignoreEnter`. Shouldn't we ignore the enter press when suggestions are hidden and not the other way around?

Also, on an enter press `this.props.onSelect` is always called. It seems to me that if we are ignoring an enter press, we should not call `onSelect`. I'd imagine:

```javascript
if (this.props.ignoreEnter) {
  event.preventDefault();
} else {
  this.props.onSelect();
}
```

With the way things are currently structured, you can, for example, hit enter immediately after focus on an empty input and it will call `onSelect`.

As a nice to have, what do you think about being able to control whether or not `ignoreEnter` is true? In my case, I would like to completely disable it because when someone selects something in my UI it advances to the next screen and I'd prefer not to have the default behavior of allowing enter when the user hasn't necessarily made a suggestion.

I apologize if I'm just misunderstanding this. Doing my best to make sense of the code. If my description is unclear, I'm happy to work through this a bit more and see how I can help. Thanks for your help!

### Expected results

onSelect is not fired for empty input. Also, as as nice to have, it would be great to allow the developer to control `ignoreEnter` like `ignoreTab`.

### Actual results

Instead of `onSelect` not being fired for empty input, what I saw was that `onSelect` was fired instead.

### Reproduction steps

1) Reload the page
2) Focus on the input
3) Hit enter

**Comment by ro-ka** [comment]
Thanks for bringing this up!

What would a use case be for `ignoreEnter` other than fixing the reported problem? There is still an open issue regarding an initial selected suggest (#85) which would justify the enter on init functionality.

Question is whether it is desired behaviour to trigger `onSelect` when there is no initial suggest (as there are none currently).

// cc @yfr

**Comment by esauter5** [comment]
First of all, thank you for your response! Second, I apologize because I copied the code from the ENTER in `input.jsx` handler incorrectly. It's actually

```javascript
        if (this.props.ignoreEnter) {
          event.preventDefault();
        }

        this.props.onSelect();
```

This `onSelect` call is not a part of an `else` like in my original code. This clears up a bit of my confusion, but I still have some questions.

If I focus on the input, `isSuggestsHidden` is set to `true`. This means `ignoreEnter` is false. Will `ignoreEnter` ever actually be `true` when this piece of code is evaluated?

My impression of `ignoreEnter` was that it would work like `ignoreTab`, which does not fire `onSelect` if it is true. In my use case, this would be helpful because I do not want to allow users to hit enter because this means they havent selected an address. This means I could receive an address string like "123" with some random coordinates depending on where that resolved. I think in my case it was somewhere like San Diego. It's important in my case to have both an accurate address string and coordinates which is why I'd like to disable enter and force the user to select a suggestion.

I understand my use case may be unique in which case I'm fine forking or whatever. Before I go do that, I just want to make sure I'm understanding how it works. Am I misunderstanding the purpose of `ignoreEnter` and how this is supposed to work or is this a bug?

Have a great day!

**Comment by ro-ka** [comment]
`ignoreEnter` will always be the inverse of `isSuggestsHidden` because it is set like this `ignoreEnter={!this.state.isSuggestsHidden}`.

Yes the naming is misleading. As there where features added it apparently differed while looking similar. `ignoreEnter` currently is only an internal variable on the input which is more expressive. The input should not fire the enter event when the selection is done in the list.

So for providing a public `ignoreEnter` the internal one should be renamed. Then we can add a public one that behaves like the `ignoreTab`.

Do you want to open a PR with these changes?

**Comment by esauter5** [comment]
Sure thing, I should have a chance to tackle this in the next week or so. In the meantime, if you have any suggestions for a new name for the internal/current `ignoreEnter`, I'd love to hear them.

**Comment by ro-ka** [comment]
Nice! Maybe the internal could be named `submitOnEnter`?

**Comment by ro-ka** [comment]
In the meantime there was a better proposal for that kind of problem in #269. Closing this in favor of the new issue.
