### ISSUE TITLE
Support for Open Street Maps Nominatim

### ISSUE THREAD

**Issue by thnkloud9** [ubilabs/react-geosuggest#234]
### Short description

After a successful implementation of react-geosuggest in our open source project I realized that using google places api would not be acceptable due to googles terms of use.  Thus, I would like to ask if adding support for Open Street Maps Nominatim service would be useful to others?  

http://wiki.openstreetmap.org/wiki/Nominatim

If so I would be happy to kick this off with an initial PR.  However, one big caveat should be mentioned that Nominatim usage in an auto-lookup field is strictly forbidden and grounds for banning ATM, which means the  behavior of the react-geosuggest component would have to be slightly modified for this case, where suggestions are presented either with a long queryDelay (still might not be acceptable for Nominatim terms of use), or onBlur instead of onAfterInputChange.

So, at the moment just wanted to get opinions if this was a feature that others would like to see here, or if it doesn't seem to make sense to include (in which case I would probably create a new component)

**Comment by oyeanuj** [comment]
@thnkloud9 What do you think about making the non-Google support more agnostic, or also be able to support solutions like [OpenCage](http://geocoder.opencagedata.com/)(also based on Open Street Maps)?

**Comment by thnkloud9** [comment]
@oyeanuj - yeah, thats a good idea, but in the meantime would be nice to get the pending PR that addresses this specific issue merged first:

https://github.com/ubilabs/react-geosuggest/pull/238

then I think would just need some renaming and documentation to be more agnostic.  With that PR as you can already pass a custom 'nominatim' object that defines its own geocode() function.

**Comment by ro-ka** [comment]
I like the idea to make it more independent on which geocoder to use. Thanks for bringing this up!

Left some comments on the PR. In general, the component should be independent of the Google Geocoder or Nominatim or OpenCage or Mapbox Geocoder.

* How could this look like?
* Use something like an interface for the geocoding so people would be free to implement their own?
* Are there geocoding interface implementations already that can be reused?

I think the API should either:
* Provide `geocodeProvider: 'nominatim'` thing and include all the possible geocoder (bloated)
* Allow to pass `geocoder: myGeocoder`. The `myGeocoder` would then need to provide a `.geocode()` function and a `.querySuggests()` function where each returns a Promise. This would require people to install another component like `react-geosuggest-geocoder-google` which get’s plugged into the main component.

What do you think?

// cc @yfr

**Comment by thnkloud9** [comment]
sounds like a good plan to me. 👍

**Comment by rajington** [comment]
We might need to replace `Geocoder` with `Place Details` anyway (#258) and the safest method might be supporting both as potential Geocoders even though they're both by Google.

**Comment by thnkloud9** [comment]
Sorry, accidentally closed my original PR, but have updated a bit to make the changes more agnostic here:

https://github.com/ubilabs/react-geosuggest/pull/259

**Comment by ro-ka** [comment]
We were discussing this internally and came to the following conclusion:
* This components main purpose is to provide a geo-suggest component.
* Other providers (Mapbox, Nomatim, …) don’t provide the suggest functionality that we expect.
* If we abstract the suggest functionality it would lead to a component that handles just that: being a suggest library that can be extended via plugins. But that is what [Select2](https://select2.github.io/) already is.
* For geocoding there exists a wide variety of libraries to use.

Therefor, **we are going to keep the component Google only** for now. But **feel free to fork** and provide a suggest that handles Nomatim or other providers.
