### ISSUE TITLE
Module not found: 'react-addons-shallow-compare'

### ISSUE THREAD

**Issue by HarrisRobin** [ubilabs/react-geosuggest#239]
### Short description

I was trying to do 
Install the plugin with npm.

### Expected results
To successfully install.

### Actual results

Instead of installing successfully, what I saw was that I got an error saying
```Module not found: 'react-addons-shallow-compare'.```

### Reproduction steps

1. use react@15.3.2
2. npm install react-geosuggest --save
3. run your app
4. Finally the error will happen

**Comment by ash-developer** [comment]
it's not an error
it's warning related to peer dependencies

**Comment by teemualap** [comment]
Before `2.0.1`, if you encounter this error, you can fix it temporarily by using a webpack resolve alias:

```
resolve: {
  alias: {
    'react-addons-shallow-compare': 'react/lib/shallowCompare'
  }
}
```

**Comment by lewisdiamond** [comment]
Same error, and it's actually an error, not a warning. My application won't run with that. I'm using CRA.
