### ISSUE TITLE
Inability to pass down ARIA attributes is an accessibility issue

### ISSUE THREAD

**Issue by HugoGiraudel** [ubilabs/react-geosuggest#241]
### Short description

I was trying to pass down ARIA attributes (namely `aria-required`, `aria-invalid` and `aria-describedby`) to the `input` element but react-geosuggest filters them out.

### Expected results

react-geosuggest should allow aria-attributes to be passed down to the `input` element. 

### Actual results

The `input` does not get any ARIA attribute.

---

If you know how to fix this and want to put me on track, I’ll be happy to submit a PR.

**Comment by ro-ka** [comment]
Thanks for bringing this up! There is [`filter-input-attributes.js`](https://github.com/ubilabs/react-geosuggest/blob/master/src/filter-input-attributes.js) which contains all the allowed attributes on input fields. Feel free to open a PR that adds the ARIA ones!
