### ISSUE TITLE
react-geosuggest does not trigger autocomplete request to Google side sometimes

### ISSUE THREAD

**Issue by junxiesc** [ubilabs/react-geosuggest#244]
### Short description

We are using react-geosuggest in the Google Map to autocomplete the place suggestion. For example, if I type "san", it will have a list of suggestions such as "Santa Monica". Currently, we experience that sometimes react-geosuggest does not have those those suggestions in an intermittent way. Here are our observations:

1. When we type and get auto-suggestions, we can see that auto-completion request is triggered.
2. Wen we type and do not get auto-suggestions, we do not see auto-complete request in the network side.

This is the auto-completion request looks like:

https://maps.googleapis.com/maps/api/place/js/AutocompletionService.GetPredictionsJson?1ssan......

Would you mind recommending some directions that we can follow to investigate on this issue? Thanks

### Expected results

I expect that by typing in the geosuggest, it should always return the suggestions.

### Actual results

We experience that sometimes react-geosuggest does not have those those suggestions in an intermittent way. 

### Reproduction steps

1. Type something in "geosuggest" input.
2. Sometimes we do not get suggestions back.

**Comment by ro-ka** [comment]
There is a throttling to limit the requests per second as it would consume a lot of the Google Maps API credits. Is it the throttling?

Can you make a video / GIF that shows the issue? Cannot reproduce.

**Comment by junxiesc** [comment]
Good point. Currently, what is the throttling limit per second? Is this limit specified in the react-geosuggest or in the map key we generated from our side?

**Comment by ro-ka** [comment]
The default is 250ms. See [`queryDelay`](https://github.com/ubilabs/react-geosuggest#querydelay). Google has some limits for queries per second, too. But those aren’t handled by the component as it is sufficient fast for typing.

Is this the reason? Can this be closed?

**Comment by ro-ka** [comment]
Reopen if this wasn’t helping.
