### ISSUE TITLE
How can I clear the suggest on Enter key press?

### ISSUE THREAD

**Issue by tsh356** [ubilabs/react-geosuggest#245]
### Short description
I'm trying to add multiple items to a list. 

### Expected results
I want to clear the suggest and the input on Enter keypress so when the user types again after pressing enter, new suggestions are displayed.d

### Actual results

When onSuggestSelect is triggered with the Enter key press, the suggest does not get cleared. I can clear the input by setting initialValue = {this.state.term}, but when typing is commenced, the suggestions are not showed.

**Comment by ro-ka** [comment]
You can listen to the [`onSuggestSelect`](https://github.com/ubilabs/react-geosuggest#onsuggestselect) and call [`clear()`](https://github.com/ubilabs/react-geosuggest#clear) then.
