### ISSUE TITLE
Move Google Places script into component

### ISSUE THREAD

**Issue by ryenbeatty** [ubilabs/react-geosuggest#25]
Hi there! This is a great component, I am building a Meteor app using this plugin, and it would be nice if the component handled the script internally, so that the component could be loaded at any time, and handle it's own dependency on the external script.

Is this something that is possible? Or should I fork and make the changes tailored to my own needs?

Thanks!

**Comment by ro-ka** [comment]
Hi! You can pass in the `google.maps` dependency, then it won’t look for a global var. See the [Readme](https://github.com/ubilabs/react-geosuggest#googlemaps) on how to use.

Does this help in your case? A fork shouldn’t be necessary.  :)

**Comment by ryenbeatty** [comment]
Oh of course! Yes that totally helps, thanks for pointing me in the right direction :)

**Comment by ro-ka** [comment]
Great!  :)
