### ISSUE TITLE
Pressing enter does not blur the input

### ISSUE THREAD

**Issue by brmenchl** [ubilabs/react-geosuggest#251]
When you press enter while typing in the input, the suggests are hidden, but the input remains focused. Then when you continue typing, the suggests remain hidden and you can't select anything. You can only return to the original behavior by manually blurring and coming back to the field.

I'm getting around this in my code by explicitly blurring the input at the end of my `onSuggestSelect` hook callback.

**Comment by brmenchl** [comment]
I can do this, although I'm wondering about the expected behavior.

Should the input blur no matter what at the end of `selectSuggest` or should we keep it when `suggest` is undefined i.e. no autocompleted suggest was selected?

**Comment by yfr** [comment]
I have the same issue with a project of ours. 

For my use-case I like to leave the focus on the input and be able to type and get new suggestions.

@ro-ka Whats your opinion?

**Comment by ro-ka** [comment]
I have no special preference here.

**Comment by brmenchl** [comment]
That also would work for my use case.

**Comment by joanrodriguez** [comment]
I have fixed your bug in this pull request: https://github.com/ubilabs/react-geosuggest/pull/340
