### ISSUE TITLE
index.d.ts file for typescript users?

### ISSUE THREAD

**Issue by brmenchl** [ubilabs/react-geosuggest#254]
Without a typedef file, typescript users have to either make their own, or do without type safety.

An (incomplete) example would look something like:

NOTE: The types that come from the Google Places API should probably just be living in that typedef. This is just my WIP typdef I'm using for my own project.

```
/// <reference path="./react/react.d.ts" />

declare module 'react-geosuggest' {

    export type GeocoderAddressComponent = {
        long_name: string;
        short_name: string;
        types: string[];
    }

    export type GeocoderResult = {
        address_components: GeocoderAddressComponent[];
        formatted_address: string;
        types: string[];
    }

    export type AddressAutocompleteMatch = {length: number, offset: number};

    export type AddressAutocompletePrediction = {
        description: string;
        matched_substrings: AddressAutocompleteMatch[];
        place_id: string,
        terms: {offset: number, value: string}[];
        types: string[]
    }

    export type Suggest = {
        label: string;
        location?: {isFixture: boolean, label: string, placeId: string};
    }

    export type GeocodedSuggest = Suggest & {gmaps: GeocoderResult};

    export type GeosuggestStyles = {
        input?: {[key: string]: any},
        suggests?: {[key: string]: string},
        suggestItem?: {[key: string]: string}
    };

    export interface GeosuggestProps {
        autocomplete?: string;
        country?: string;
        initialValue?: string;
        placeholder?:string;
        types?: string[];
        required?: boolean;
        inputClassName?: string;
        name?: string;
        style?: GeosuggestStyles;
        getSuggestLabel?(suggest: AddressAutocompletePrediction): any;
        onChange?(value: string): void;
        onSuggestSelect?(suggest: Suggest): void;
        skipSuggest?(suggest: AddressAutocompletePrediction): boolean;
    }

    export interface GeosuggestState {
        ignoreBlur?: boolean;
        isSuggestsHidden?: boolean;
        suggests?: Suggest[];
        userInput?: string;
    }

    class Geosuggest<I> extends __React.Component<GeosuggestProps & I, GeosuggestState> {
        selectSuggest: (suggest?: Suggest) => void;
        geocodeSuggest(suggest: any): void;
    }

    export default Geosuggest;
}
```

**Comment by ro-ka** [comment]
That would be great! Do you know an easy way to generate these from the JSDoc annotated? Generating automatically would help regarding duplication and out of date definitions.

**Comment by brmenchl** [comment]
https://github.com/jsdoc3/jsdoc/issues/437
It looks like there isn't a near-term solution for this. I agree, especially because this project isn't being developed in Typescript, the typedef is likely to quickly go out of date. I'll keep looking around, but I have an up to date def I'll do a PR with now.

**Comment by ro-ka** [comment]
And what about the linked https://github.com/englercj/tsd-jsdoc?

**Comment by brmenchl** [comment]
I looked into it, and tried to run it on the codebase, but it encountered numerous errors and spat out a blank typedef. It says it's 'Highly Experimental', so I'm thinking it would be wise to revisit it after some time.

**Comment by ro-ka** [comment]
A PR with a manual definition file would be great then!   :)

**Comment by brmenchl** [comment]
Great, I'm on it.

**Comment by brmenchl** [comment]
Sorry for the delay.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-geosuggest/index.d.ts

I'm not sure if/when the types will be published, but they'll be available through DT from now on.  This should be ready to close.

**Comment by ro-ka** [comment]
Very nice, thanks @brmenchl! We can include the types directly in this project, right? Then one doesn’t need to install the types separately, which can cause versioning issues…

Started with TypeScript some months ago, so I’m a bit firm in it now, too.  😃

**Comment by brmenchl** [comment]
Yeah, it would be better to throw it in here. I can do that that.

**Comment by ro-ka** [comment]
Nice! Just create a PR.  😃

**Comment by gillyb** [comment]
@brmenchl - Are you still planning on doing this ?
If so, then there's a slight fix you should make in the DT files, On this line:
 https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-geosuggest/index.d.ts#L36
It should be:
```
onFocus?(value: any): void;
```

**Comment by brmenchl** [comment]
@gillyb thanks for the reminder, I completely forgot about this. I just spent a couple of hours to migrate the types into this repo, but I'll be honest, the Typescript docs are detailed, but a bit confusing on how to write typedef tiles for different scenarios. I'm not sure how to use React and googlemaps types within the react-geosuggest repo typedef without adding them to the devDependencies. Is that the current practice?

**Comment by gillyb** [comment]
@brmenchl Me being pretty new to Typescript myself, I'm not 100% sure, but I do believe that's the current practice.
Either way, adding the `@types` packages to `devDependencies` won't do any harm, since they won't be installed on production environments, and they won't be used when actually bundling either, so I think it's safe.

**Comment by brmenchl** [comment]
@gillyb I was about to put together a PR for this but I saw this:
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

If your package is not written in TypeScript then the the preferred approach is to publish to the @types organization on npm.

Unless you have a specific request for it in this repo, I think I'm going to just make the type fix on DT.

**Comment by gillyb** [comment]
Hey @brmenchl - Sure, no problem. I didn't know that was the recommended approach. (I personally rather have the types inside the library, but if that's the convention, then let's go along with it) :+1:

**Comment by ro-ka** [comment]
Publish on @types then. In case this is rewritten in TypeScript we can include them directly. Thanks for the efforts!
