### ISSUE TITLE
Types property doesn't seem to work as expected with some values

### ISSUE THREAD

**Issue by koriner** [ubilabs/react-geosuggest#255]
According to the documentation, the component supports a ```types``` Array which specifies which types of places to return. I'm not sure if I'm using this incorrectly or if it's not working properly.

The Google docs (https://developers.google.com/maps/documentation/javascript/reference#AutocompletionRequest) specify the following types are available: ```geocode | regions | establishment | cities``` - however, only the ```geocode``` option seems to work for me.

The use case is that I'm trying to limit a particular search to a suburb level (i.e. a particular suburb within Australian cities), e.g. "Brunswick" in Melbourne, Australia.

I'm not positive whether I should be using the 'regions' or 'cities' option but neither of those seem to return any results anyway.

I'm using the component like so:

```
<Geosuggest
  placeholder="Start typing an address..."
  country="au"
  types={['regions']}
  onSuggestSelect={::this.selectOption}
/>
```

Doing this gives zero results appearing in the popup list. Using 'geocode' works but also includes specific addresses which I'd like to avoid if possible.

Is this the correct way to do it? 

Thanks!

**Comment by ro-ka** [comment]
It should work as you are trying to do. Google changed their geocoder behaviour, maybe this is affected by this?

**Comment by koriner** [comment]
I'm not sure what you mean exactly - what did they change?

**Comment by koriner** [comment]
Argh, never mind! It's working. Apparently I just can't read.

I just needed to include the parentheses in the string, i.e. ```types={['(regions)']}``` as per the docs.

D'oh.

**Comment by ro-ka** [comment]
Great! Didn’t spot that at first neither.

**Comment by luisfuertes** [comment]
I try to return only localities, but i try to add `types = { ['(cities)'] }` and `types = { ['cities'] }`. But it return streets, and complete address too. 

Can i restrict that?
