### ISSUE TITLE
Add button/option for reverse geolocation

### ISSUE THREAD

**Issue by sandervanhooft** [ubilabs/react-geosuggest#257]
I am trying to implement reverse geolocation lookup (a.k.a. "What's the location of this device?") in a button next to this component, and then populate the geosuggest component with that information.

See [here](https://www.snappcar.nl) for example (not by me, probably not React).

I think this is a more common use case, so does anyone have experience with this, perhaps some example code to share?

I think it also would be an interesting enhancement to the Geosuggest component.

**Comment by sandervanhooft** [comment]
Also see #85

**Comment by ro-ka** [comment]
We are not planning to include such a button. This can be realized easily by a separate button that updates the Geosuggest via the [`update(value)`](https://github.com/ubilabs/react-geosuggest#updatevalue) function
