### ISSUE TITLE
Problem in changing the maxHeight of suggest's style

### ISSUE THREAD

**Issue by sureshmurali** [ubilabs/react-geosuggest#267]
### Short description

I was trying to change the maxHeight of suggestion list

```
  <Geosuggest style={{ 'input': {},'suggests': {'maxHeight':'4em'},'suggestItem': {} }} 
                         queryDelay='0' 
                         placeholder='Event location' 
                         initialValue='' 
                         onSuggestSelect={this.suggestLocation}
                         onChange={this.storeLocation}/>
```

### Expected results

I expected that it would decrease the height of the suggestion list

### Actual results

It decreased the height of the suggested list. But it doesn't retract back or hide after after selecting a suggested place.

### Reproduction steps

1. Add style for "suggests"

`'suggests': {'maxHeight':'4em'}`

2. Type location name and select a suggested place.

3. BUG -> Suggestion list doesn't retracts back and stays in same specified height (4em) 

### Additional Information

This is how it looks **after selecting the suggested place**
<img width="143" alt="screen shot 2017-01-20 at 11 20 22 am" src="https://cloud.githubusercontent.com/assets/8108361/22133254/8c2944dc-df02-11e6-92b2-5311c02d4010.png">

Problem is element style's css (max-height:4em) overrides .geosuggest__suggests--hidden (max-height:0px)

**Comment by ro-ka** [comment]
You should either use CSS or the inline styles. Pick one and stick with that.
