### ISSUE TITLE
Hitting 'Enter' breaks the dropdown

### ISSUE THREAD

**Issue by StrikoMirko** [ubilabs/react-geosuggest#268]
### Reproduction steps

1. Click inside the geosuggest input
2. Type London
3. Press enter
4. Start typing again, or backspace the current chars
5.The dropdown stays invisible and will not work unless you click outside input then inside again.

From what I have gathered the problem is in state.isSuggestsHidden variable.

When you hit enter it is set to true and hides the dropdown, but when you continue typing it is still set to true and the dropdown remains hidden.

**Comment by ro-ka** [comment]
Can reproduce, needs a solution that’s not breaking.

**Comment by blakeyoder** [comment]
@ro-ka I am running into this problem as well. Mind if I take this one?

**Comment by ro-ka** [comment]
@blakeyoder Yes, you’re free to find a solution for this!

**Comment by ro-ka** [comment]
Testing the current version this is fixed in the meantime. Reopen if still an issue.
