### ISSUE TITLE
unexpected behaviour from ignoreTab

### ISSUE THREAD

**Issue by nadangergeo** [ubilabs/react-geosuggest#269]
I was trying to do ignore tabs using ignoreTab, but it did not work as expected.  I need to ignore tabbing completely (in other words, also prevent the default event, so that it doesn't go to the next element). Al though this is probably not the desired result by everyone.

Suggestions:
alt. A) expose the onKeyDown event from input. That way, we get a lil' better control when needed. Could help with #232

alt. B) Implement preventTabToPrevious & preventTabToNext (or something like that)?

Awesome repo! Cheers :)👍

**Comment by ro-ka** [comment]
Option A sounds reasonable. Feel free to submit a PR implementing this!
