### ISSUE TITLE
Expected behavior of ARROW DOWN

### ISSUE THREAD

**Issue by ming-soon** [ubilabs/react-geosuggest#271]
What is the expected behavior when pressing a arrow-down key on input after entering some text?

Say, if I enter 'Ne' and press a arrow-down key, does it have to display the suggestion list and select the first item by default?

For now, when the suggestion list is invisible, it pops up and there is no selection.

**Comment by ro-ka** [comment]
It is expected that the list is already open and it selects the first entry.
