### ISSUE TITLE
How to include Zip Code in the address label

### ISSUE THREAD

**Issue by tenzin-lama** [ubilabs/react-geosuggest#272]
### Short description

I need to show zip code in the address label but it is not there by default and I also tried getSuggestLabel but that did not help either. How can I achieve the following?

### Expected results
I would like to have label like this: 123 Main Street, San Francisco, CA 94001, United States

**Comment by Shobhit1** [comment]
My suggestion would be to make sure that this is based on a prop called `showZipInLabel`

**Comment by ro-ka** [comment]
We won’t introduce a new prop, but there was [`renderSuggestItem`](https://github.com/ubilabs/react-geosuggest#rendersuggestitem) added recently. Does this help?

**Comment by lopezdp** [comment]
> 
> 
> My suggestion would be to make sure that this is based on a prop called `showZipInLabel`

I dont see `showZipInLabel` nor can `ctrl + f` find it....

**Comment by lopezdp** [comment]
@ro-ka i dont really even need it in my label, I just need to access the ipCode associated to the label... great tool by the way.

**Comment by ro-ka** [comment]
Ah, you mean you want to get access to the props passed in with the fixtures? There is a similar issue now: #413.
