### ISSUE TITLE
calls to geocodeSuggest geocode service ignore country attribute

### ISSUE THREAD

**Issue by jipd** [ubilabs/react-geosuggest#274]
### Short description

When trying to autocomplete an address it calls the geocoder.geocode service with just an address, the region property needs to be set to the value in props.country when there is one. 

### Expected results

Addresses returned from the geocoding service should be restricted by country

### Actual results

Addresses are not restricted to country when this service is called

### Reproduction steps

1: Open a geosuggest prompt which has a targeted country (not the US)
2: Start typing a postcode and hit enter before the service has time to resolve
3: Notice network calls to the geocode service omit the set country / region parameter, however calls to the Autocompletion service do.

### Additional Information

adding the region parameter within the geocoder.geocode call fixes this issue

**Comment by ro-ka** [comment]
Thanks for reporting!
