### ISSUE TITLE
onChange is passing input value instead of event object

### ISSUE THREAD

**Issue by richcsmith** [ubilabs/react-geosuggest#276]
### Short description

I am passing an `onChange` handler to `<Geosuggest />`, and it's passing the input's value as the sole argument, instead of React's `SyntheticEvent` object.

This is pretty straightforward, so I don't think reproduction steps are necessary, but here's an example of what I'm doing:

```js
import Geosuggest from 'react-geosuggest'

export default AddressInput extends Component {
  componentWillMount() {
    // Asynchronously load Google Maps
  }

  onChange(event) {
    console.log(event)// Will output the current value of the Geosuggest input
  }

  render() {
    return (
      <Geosuggest
        onChange={this.onChange} />
    )
  }
}

```

**Comment by mozmorris** [comment]
Even though it's perhaps not clear in the documentation, I understand this is the expected behaviour and would be a breaking change if the event was passed.

`Type: Function Default: function(value) {}`

The `onKeyPress` is passed the keypress event, is that of any help?

**Comment by ro-ka** [comment]
This is the expected behaviour and indeed would be breaking. No intent to change. Thanks for clarifiying @mozmorris!
