### ISSUE TITLE
Geocoding results

### ISSUE THREAD

**Issue by Exomnius** [ubilabs/react-geosuggest#279]
Use case: 
I need to restrict my suggestions and resulting coordinates to one country.

Issue:
I added the country property which works for the suggestions, but not for the result (when I type a postal code and press enter).

Question:
Is it possible to pass geocoding information to the geosuggest?

Regards
Cornel Janssen

**Comment by ro-ka** [comment]
Thanks for reporting, there is a similar issue in #274. Closing this as a duplicate.
