### ISSUE TITLE
Enter press fires onSuggestSelect without any suggest active

### ISSUE THREAD

**Issue by shaunlandau1973** [ubilabs/react-geosuggest#290]
### Short description

Type some input and press enter and onSuggestSelect fires for some random address. Didn't select any of the suggestions ... why does the onSuggestSelect fire?

### Expected results

Pressing enter should do nothing unless an item is active in the suggestions list. Someone mentioned ignoreEnter prop ... this seems to have no effect for me and is not documented.

**Comment by ro-ka** [comment]
This is the expected behaviour as the Google Geocoder might return a result when there is none selected / found in the Autocomplete.
