### ISSUE TITLE
Provide an example of how to go from a city to lat long

### ISSUE THREAD

**Issue by posix4e** [ubilabs/react-geosuggest#293]
### Short description

We are using your package but we provide our own infra for converting the searched city name to lat/long

### Expected results

I expect a clear example of how to do this.

### Actual results
I am totally confused if you do this or not

### Reproduction steps

1. Read the docs
2. Implement the package

**Comment by ro-ka** [comment]
This component queries the `google.maps.places.AutocompleteService` for matches to the entered user input and returns those. If a random string is entered which didn’t result in a match at the mentioned API, it tries to geocode this string against the `google.maps.Geocoder`. Additionally it is possible to add fixures (predefined suggestions by the user) which can also be filtered according to the user input.
