### ISSUE TITLE
Missing address_components

### ISSUE THREAD

**Issue by tcomaj** [ubilabs/react-geosuggest#295]
### Short description

**[onSuggestSelect](https://github.com/ubilabs/react-geosuggest#onsuggestselect)** event does not return the complete response in gmaps.address_components. The response is missing some components when I compare react-geosuggest response against the response in [your jQuery plugin](https://github.com/ubilabs/geocomplete) or against original[ Google Place Autocomplete response](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete).

### Expected results
I expect to have an identical response in both your products. The response should be identical with Google Place Autocomplete.

### Actual results
Please check out this example:
![responses](https://cloud.githubusercontent.com/assets/1686806/25555655/b303671c-2cec-11e7-8458-ee481894e531.jpg)

I tried to figure out this thing by changing the property **[types](https://github.com/ubilabs/react-geosuggest#types)**. I couldn't get the complete response with all those address_components, that I can get in your jQuery plugin or in Google Place Autocomplete.

If you need more info please let me know. Thank you! You doing a great job! Keep it up!

**Comment by ro-ka** [comment]
The results returned is what Google gives us. `geocomplete` (the jQuery plugin) uses the `google.maps.places.Autocomplete` API and `react-geosuggest` uses the `google.maps.places.AutocompleteService`. We cannot alter what Google returns.
