### ISSUE TITLE
Automatically Select the Activated Suggest (using autoActivateFirstSuggest)

### ISSUE THREAD

**Issue by cant89** [ubilabs/react-geosuggest#296]
Hi, I have enabled autoActivateFirstSuggest and I was trying to automatically Select the Activated Suggest, or when the activation happen, or when the user blur the input. How can I do?
The goal is that when the user click on submit, the input has always a geo selected, because often happens that people write a city without having care to select a result.

**Comment by ro-ka** [comment]
The auto select can happen on blur but the component doesn’t know the parents and the container so it’s not possible to hook into the submit of some parent.
