### ISSUE TITLE
Add Ability to pass custom suggestionItem component

### ISSUE THREAD

**Issue by th3fallen** [ubilabs/react-geosuggest#298]
### Short description

I was trying to change how a suggestion was formatted like so
```      
 getSuggestLabel={(suggest) => (
            <span>
              <div className="name">
                {suggest.structured_formatting.main_text}
              </div>
              <small>{suggest.structured_formatting.secondary_text.replace(', United States', '')}</small>
            </span>
          )}
```

### Expected results

I expected that they would be formatted correctly (they are) and be able to select one without issue

### Actual results

but when i select one the value changes to [Object object]

### Reproduction steps
1. add getSuggestLabel method above
2. Select suggestion
3. see error

### Additional Information

```
http://th3fallen.d.pr/yfOo2
```

**Comment by ro-ka** [comment]
A new prop [`renderSuggestItem`](https://github.com/ubilabs/react-geosuggest#rendersuggestitem) was added which solves this.

**Comment by AndrewHamm** [comment]
@ro-ka but in `renderSuggestItem` we don't have access to `structured_formatting` so I don't think it actually solves the problem. 

Since we can no longer send objects from `getSuggestLabel` how can we cleverly split up the text for styling?
