### ISSUE TITLE
React Component Not Found

### ISSUE THREAD

**Issue by 14850842** [ubilabs/react-geosuggest#3]
Good day,

Having an issue with the module not found.

I call it in app.jsx

var Geosuggest = require('geosuggest')

In console I get the following error:

ERROR in ./components/app.jsx
Module not found: Error: Cannot resolve module 'geosuggest' in /Users/sergiopellegrini/Sites/recipes-flux/client/components
resolve module geosuggest in /Users/sergiopellegrini/Sites/recipes-flux/client/components
  looking for modules in /Users/sergiopellegrini/Sites/recipes-flux/node_modules
    /Users/sergiopellegrini/Sites/recipes-flux/node_modules/geosuggest doesn't exist (module as directory)
    resolve 'file' geosuggest in /Users/sergiopellegrini/Sites/recipes-flux/node_modules
      resolve file
        /Users/sergiopellegrini/Sites/recipes-flux/node_modules/geosuggest doesn't exist
        /Users/sergiopellegrini/Sites/recipes-flux/node_modules/geosuggest.js doesn't exist
        /Users/sergiopellegrini/Sites/recipes-flux/node_modules/geosuggest.jsx doesn't exist
[/Users/sergiopellegrini/Sites/recipes-flux/node_modules/geosuggest]
[/Users/sergiopellegrini/Sites/recipes-flux/node_modules/geosuggest]
[/Users/sergiopellegrini/Sites/recipes-flux/node_modules/geosuggest.js]
[/Users/sergiopellegrini/Sites/recipes-flux/node_modules/geosuggest.jsx]
 @ ./components/app.jsx 11:17-38

I then renamed the module to react-geosuggest but then get the following:

Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null

Your assistance will be much appreciated.

**Comment by ro-ka** [comment]
I’m sorry but I cannot replicate the issue… Can you provide a bare minimum example where the error occurs?

**Comment by 14850842** [comment]
```javascript
// React
var React = require("react");

var Geosuggest = require("geosuggest");

// Router
var Router = require("react-router");
var RouteHandler = Router.RouteHandler;

// Child Components
var Nav = require("./nav");

// Component
var App = React.createClass({
  displayName: "App",
  propTypes: {},
  mixins: [],

  getInitialState: function () { return null; },

  componentWillMount: function () {},

  componentWillUnmount: function () {},

  render: function () {
    return (
      <div className="epicureContainer">
        <Geosuggest/>
      </div>
    );
  }
});

module.exports = App;
```

In console:

```
ERROR in ./client/components/app.jsx
Module not found: Error: Cannot resolve module 'geosuggest' in /Users/sergiopellegrini/Sites/recipes-flux/client/components
 @ ./client/components/app.jsx 4:17-38
```

**Comment by loris** [comment]
Use `var Geosuggest = require("react-geosuggest");` instead

**Comment by ro-ka** [comment]
@14850842 Does that help? Is it working now?
@loris Thanks for answering!

**Comment by 14850842** [comment]
Got a step further.

Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
warning.js:48 Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactory
ReactClass.js:842 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null
(Something is calling a React component directly)

**Comment by ro-ka** [comment]
Did you follow the suggestions at the link? (https://fb.me/react-legacyfactory)
Are you using JSX or plain JS?

**Comment by 14850842** [comment]
Calling as prescibed using JSX.

**Comment by ro-ka** [comment]
As far as I understand the link it is fine the way it is. Does that error still occur when you use the example above?

Btw., I’ll update the readme because of the wrong `require` statement. Thanks for reporting. :)

**Comment by 14850842** [comment]
Thanks. I got it running now.
