### ISSUE TITLE
Expose the [input]

### ISSUE THREAD

**Issue by bradennapier** [ubilabs/react-geosuggest#302]
There are quite a few props that an input provides and there is currently no way to do this.  For example, I generally have the first click select all the text of the input (input.select()) but it is impossible to do this for this input specficially.

Perhaps it would be worth allowing to pass a custom input to be used?

**Comment by bradennapier** [comment]
This does appear to work but kind of hacky

```this.props.suggestRef.refs.input.refs.input.select()```

**Comment by ro-ka** [comment]
It is possible to pass props to the input. Actually all props that match the list in [`filter-input-attributes.js`](https://github.com/ubilabs/react-geosuggest/blob/master/src/filter-input-attributes.js) get passed through. `.select()` isn’t a prop, though. The way you’re accessing the input is not official and depending on internal declaration which could change.

That said, we won’t accept custom inputs passed in.
