### ISSUE TITLE
Make `autocomplete` a prop instead of forcing it to be turned off

### ISSUE THREAD

**Issue by treyhuffine** [ubilabs/react-geosuggest#303]
### Short description

When Google autofills our name/address form, it leaves the address field blank since `autoComplete` is set to off.

### Expected results

Use a prop to control autocomplete because this is undesired behavior for many use-cases. If someone starts typing their name in a name field and clicks autocomplete, we should expect it to also fill in the address field.

**Comment by janziemba** [comment]
+1
