### ISSUE TITLE
highlightMatch w/ Postal Codes Not Working

### ISSUE THREAD

**Issue by hwhelchel** [ubilabs/react-geosuggest#316]
### Short description

I was trying to do use Geosuggest with the highlightMatch feature turned on to search for postal codes.

### Expected results

I expected that by going to the page 'http://ubilabs.github.io/react-geosuggest/' and typing in '30342' then it would display a list of results with the first one showing "Atlanta, Ga, 30342, United States" would happen.

### Actual results

Instead of seeing "Atlanta, Ga, **30342**, United States", what I saw was that the first suggestion was "Atlanta, Ga, **ta, Ga**, United States" instead.

### Reproduction steps

1. Go to 'http://ubilabs.github.io/react-geosuggest/'
2. Type in a zipcode like '30342'
3. See the first suggested item not render correctly.

### Additional Information

If one turns off highlightMatch it displays the appropriate postal code.

![postal_code](https://user-images.githubusercontent.com/4792375/27201596-373bb632-51ec-11e7-8d30-d6682cc6fb2d.gif)

**Comment by ro-ka** [comment]
Thanks for the report, fixed in `2.3.1`.
