### ISSUE TITLE
Cache requests to google Api

### ISSUE THREAD

**Issue by izziaraffaele** [ubilabs/react-geosuggest#32]
From google doc

Geocoding is a time and resource intensive task. Whenever possible, pre-geocode known addresses (using the Google Maps Geocoding API described here or another geocoding service), and store your results in a temporary cache of your own design.

A basic implementation can be found on the PR I submitted https://github.com/ubilabs/react-geosuggest/pull/29

**Comment by ro-ka** [comment]
That’s great – could you prepare a PR with cherry picked changes for the caching?

**Comment by ro-ka** [comment]
The browser caches the Google requests already. So no need for an individual implementation.

See the screenshot. I typed “Rio” twice:
![](https://cloud.githubusercontent.com/assets/840022/15610575/354c296e-2426-11e6-995b-3e8421414387.png)
