### ISSUE TITLE
How to expand data object available to renderSuggestItem?

### ISSUE THREAD

**Issue by domhede** [ubilabs/react-geosuggest#323]
I am trying to apply a custom design for the suggestion list.  

Whilst the renderSuggestItem function is really helpful (this whole library is awesome, thank-you!),  it would be great if I could isolate the items within the object that renderSuggestItem receives.  Is there another way to do this currently?  Including the gmaps object that onSuggestSelect receives would be ideal.

This would allow for specific  rendering and styling.
eg. country could be styled differently to street address.

**Comment by ro-ka** [comment]
The `google.maps.autocompleteService.getPlacePredictions()` result doesn’t contain geometry information such as countries. Doing a geocode request for each suggest is not an option. So you’ll have to work with what is currently available.
