### ISSUE TITLE
allow extra options in suggestion dropdown

### ISSUE THREAD

**Issue by mbohal** [ubilabs/react-geosuggest#324]
### Short description

I would like to allow my application to accept addresses not known to google. Our client says that it is an actual use case and that they need it.

### Expected results

The proposed solution from our UX team is to have an extra option in the suggestion dropdown that would read something like `Address not listed? Enter manually`. Clicking it would hide the geosuggest field and show some other form.

I think, that if we could pass an extra option to the suggestion dropdown with label and callback it will work.  

### Actual results

This is currently not supported.

### Additional Information

I'm willing to work on this and submit a PR. Is there any interest in this and is there any chance of having the PR merged?

**Comment by ro-ka** [comment]
This component finds addresses on Google or your predefined fixtures. If that address isn’t found you still can enter an address as you like, even if nothing got found. It’ll try to geocode that and if that didn’t help it’ll return that entered string without a location added.

For the scope of this component adding an option as you proposed is a to specific need which we don’t want to handle in this component. Can’t you solve this somehow else?

**Comment by mbohal** [comment]
The problem is that google usually finds something, but I, as a user, do want to indicate that my address is not among the suggested results. I don't see a way how to handle this with `react-geosuggest` at the moment.

I understand our use case might be too specific though and I will find another solution. If I end up forking and adding the feature it in the fork, can I make a PR so you can reasses ? I will completely understand if you refuse the PR.

Thank you for the prompt answer.

**Comment by ro-ka** [comment]
You’re free to fork, of course. We’ll take a look at the PR but I suppose it’s to specific, sorry. It’s hard to keep the component more or less minimal as there are so many different requests.

You can easily import from github, too, in case you don’t want to publish to npm.
