### ISSUE TITLE
Tab complete ignores country prop restriction

### ISSUE THREAD

**Issue by lolcookie** [ubilabs/react-geosuggest#325]
### Short description

Autocomplete only Australian addresses with country='au' prop, but pressing tab autocompletes to any address.

### Expected results

The user can only select from australian addresses and tab moves to next input field

### Actual results

If the user presses tab the form ignores country prop and autocompletes input to US address etc

### Reproduction steps

1. Set country restriction
2. Type different country address
3. Press tab

**Comment by ro-ka** [comment]
The country prop is passed to the Google API and doesn’t restrict but prioritize the results. The component shows what Google is returning. There is no way this component can alter the Google Autocomplete behaviour.
