### ISSUE TITLE
Each child in an array should have a unique key

### ISSUE THREAD

**Issue by yns01** [ubilabs/react-geosuggest#326]
### Short description

On the live demo, when I start typing an address I get the following warning: 

`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of t`

I am pretty sure someone must have raised this before, but I couldn't find anything in the closed issues.

**Comment by ro-ka** [comment]
The problem appears to be the highlight match function. It splits the suggest label in an array and replaces the match with an JSX.Element (`<b>`). Apparently React complains about the array with individual strings missing a key. Not sure how to solve: adding a span with a key to each doesn’t make sense.

**Comment by yns01** [comment]
I had a look at the code. The issue comes from the `makeBold` function which is expecting a `key` parameter. However, it's called without: ` this.makeBold(suggest.label.substring(start, end))`

I'll submit a PR @ro-ka

**Comment by yns01** [comment]
PR #330
