### ISSUE TITLE
react-addons-shallow-compare is deprecated, prefer React.PureComponent

### ISSUE THREAD

**Issue by adrienharnay** [ubilabs/react-geosuggest#329]
Hi,

Just saw react-addons-shallow-compare was a new dependency introduced in the last version.

From the docs: https://www.npmjs.com/package/react-addons-shallow-compare, it is deprecated and React.PureComponent should be used instead.

Thanks,

**Comment by ro-ka** [comment]
Thanks for reporting, that needs to be updated, that’s true.

**Comment by ro-ka** [comment]
`react-addons-shallow-compare` isn’t part of this project anymore.
