### ISSUE TITLE
Add props validation 

### ISSUE THREAD

**Issue by izziaraffaele** [ubilabs/react-geosuggest#33]
It's very common in the React world to use React.PropTypes not just for validation of component's props but also to have a clear picture of all the props that a component manage and for documentation. 

In getDefaultProps is better to define just conditional props since mandatory props will be in any case overwritten.

An inspiration can be found on the PR I submitted #29

**Comment by ro-ka** [comment]
A breaking change as far as I can see would be that the radius is required as a number, not a String as it is now. What else would be affected? Would like to bundle breaking changes for a master release.

**Comment by ro-ka** [comment]
Released in `1.19.0`.
