### ISSUE TITLE
Compliments!

### ISSUE THREAD

**Issue by bradennapier** [ubilabs/react-geosuggest#331]
Just wanted to provide a compliment here.  Nothing is more satisfying (well relatively considering...) than running into a problem with a component that seems to be pretty abstract then coming to the page and seeing that a solution is already provided in the documentation.  In this case you have the tab toggling the select which was killing my form but since you provided a prop to get around it -- simple fix! 

The field right above the geo suggest has a component that had to be modified to not break general form logic with their defaults... so... kudos!  Thanks a ton for the wonderful component!

**Comment by ro-ka** [comment]
Wow, thanks a lot!  😊
