### ISSUE TITLE
Retrieving suggests list

### ISSUE THREAD

**Issue by wasong** [ubilabs/react-geosuggest#338]
I was trying to find a way to retrieve the list of suggestions so I can list them somewhere else on the page. I looked for a prop that would allow me to get the array back on search but could not find one.

I looked through the closed issues and documents but could not find anything 😭 
I also forked and tried to modify it but could not get the Component from my forked github package.
Could anyone point me in the right direction?

Sorry if I worded this incorrectly or if this is inappropriate in issues, please delete if so!

**Comment by ro-ka** [comment]
You could add a prop `onSuggests` that get’s triggered when the suggest list changes.

It’s not inappropriate, that’s what the issues are for.  😉

**Comment by davidfurlong** [comment]
@ro-ka `onSuggests` isn't documented in the README, and a quick code search shows its only in an open PR https://github.com/ubilabs/react-geosuggest/pull/348

What needs to get done to release this?

**Comment by davidfurlong** [comment]
My particular use case is: 

On no results I want to show a message. Currently very tricky, combining onNoResults & onChange as theres no `onSuggests`

**Comment by ro-ka** [comment]
Oh, sorry, I thought it was merged already. Did a review with some change requests, but nothing happened since then…

**Comment by davidfurlong** [comment]
> Oh, sorry, I thought it was merged already. Did a review with some change requests, but nothing happened since then…

Ok I'm doing a fork and fixing the PR

**Comment by ro-ka** [comment]
PR is merged, closing this.
