### ISSUE TITLE
Is there a way to disable enter key?

### ISSUE THREAD

**Issue by diegovillacis10** [ubilabs/react-geosuggest#345]
### Description

We are using Geosuggest in a project and we have a business requirement to take no action when user presses enter key.

We were investigating the current props and we couldn't find anything specific to ignore the enter key (only the `ignoreTab`)

We managed to implement this by using `onKeyDown` prop, like the following example:
```JSX
const _onKeyDown = event => {
    if (event.key === 'Enter') {
      throw new Error('Enter key not allowed')
    }
}

<Geosuggest country='us' onKeyDown={_onKeyDown} />
```

### Doubts

Even though this works, we don't think throwing an error is the best solution :)
I am wondering if is there a better existing solution?

Also, we found out some related issues (#232 and #269), but we are not sure what was the final conclusion of them. 

So, I'd like to know if you are open to add a new property called `ignoreEnter` that would do the above functionality (like mentioned in [this comment](https://github.com/ubilabs/react-geosuggest/issues/232#issuecomment-267086699)). If yes, I am more than happy to submit this pull request :)

**Comment by pamelipluas** [comment]
Hey @diegovillacis10 looks like something I need for my project too. I hope can me fix soon.

**Comment by ro-ka** [comment]
There’s no way yet, except the hack you found.  :)  You’re free to add a pull request!

Sorry for the long delay, I was on parental leave.  👶

**Comment by viniciusffj** [comment]
Great @ro-ka 

We will be submitting a PR next week
