### ISSUE TITLE
Follow react best practice and improve the separation of concerns 

### ISSUE THREAD

**Issue by izziaraffaele** [ubilabs/react-geosuggest#35]
Here there are some points I would like to highlight

- props in getInitialState is an Anti-pattern https://github.com/ubilabs/react-geosuggest/blob/master/src/Geosuggest.jsx#L38   -> https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html

- To respect Single Responsibility Principle the input should have its own component and the same the list. This helps maintaining the code, replacing parts of the component and it could also improve component customization... For example would be easier to integrate my PR if all components were split correctly from the start. Decoupling is always better. 

- Google api services should not be part of the state. Instead they should be members of the component. State is meant for mutable data not for third party libraries. If you never see setState({foo:"bar"}) but you have "foo" defined  in your state you should start thinking you're doing something wrong ;)

- As a convention I just prefer to have the render() method ALWAYS a the bottom, lifecycle methods at the start of the file in the order they are called, component methods that are exposed just after lifecycle methods and in the middle private methods prefixed with _. You'll notice that it's not just my convention but it's what most of the people use today. See for example how FB guys write their components https://github.com/facebook/fixed-data-table/tree/master/src

These stuff can be found in my PR https://github.com/ubilabs/react-geosuggest/pull/29

**Comment by ro-ka** [comment]
Will think about a better structure and take a look at your implementation.

**Comment by ro-ka** [comment]
I restructured the code to address this (finally).
* list and input have their own components now
* render is at the bottom
* Google API is not part of the state
* Except for the `initialValue` there is no prop as state. But that one doesn’t make sense to use as a prop in general, as that would mean that the user handles the essential input changes…
