### ISSUE TITLE
LastPass captures the arrow events

### ISSUE THREAD

**Issue by xedef** [ubilabs/react-geosuggest#351]
### The issue
I use LastPass (and I guess a great deal of people do). I noticed that the arrow down to move around the suggestions is first captured by LastPass instead of GeoSuggest component.

![image](https://image.ibb.co/kovKeQ/Untitled.gif)

### The fix
This is solved if the attribute `data-lpignore="true"` is added to the `input`.

### Possible ways to fix this
1. Hardcode `data-lpignore` attribute. I can't imagine a scenario in which we would like to let LP to get in the way.
2. Add `data-lpignore` to the allowed attributes list and let the developer customize it as an extra parameter
3. Add a new object property (`customInputAttributes`?) to let the developer pass all the attributes he/she wants to the `input` that might override allowed attributes list. 

I would opt for the third option as the other ones are too specific for LastPass, besides that when we bump into another similar case, we should update the code again.

I can tackle this. Just let me know your thoughts.

**Comment by ro-ka** [comment]
Hi! Thanks for bringing this up. It is definitely not desired to have it there. Hardcoding seems not ideal. What about other extensions that behave similar? We’d have to add a lot of attributes…

As React changed the handling of attributes, we should rethink them in general. Maybe remove the whitelist? Read more here: https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

**Comment by ro-ka** [comment]
Closing this because missing feedback.
