### ISSUE TITLE
Looser React versioning

### ISSUE THREAD

**Issue by holman** [ubilabs/react-geosuggest#355]
Any chance you could [loosen up the React dependency](https://github.com/ubilabs/react-geosuggest/blob/ec4c0abd108b3729294907fe8d12074cc62d27e2/package.json#L17) for those of us on React 16? Everything seems pretty fine and peachy on 16; this is a very minor point but then we wouldn't get the `has incorrect peer dependency` errors here.

Cheers! Love the library.

**Comment by ro-ka** [comment]
Thanks for the issue and the kind words!  😃 

I added React 16 to the peer dependencies. Or would you suggest anything else to loosen the dependency?

**Comment by holman** [comment]
Think that should do it, go for it! :+1:
