### ISSUE TITLE
German Address with letters after street numbers wrongly converted

### ISSUE THREAD

**Issue by Ahakke** [ubilabs/react-geosuggest#357]
Hello, 

when I am selecting the address Albrecht-Dürer-Straße 120a, Nürnberg, Deutschland

the component returns 8 address elements with the street number 120 but not the exact street number 120a.

please change this integer to a string capable of dealing with letters after numbers. In Germany, this is very common.

Thank you

**Comment by ro-ka** [comment]
The input is passed directly to the Google APIs and shows the results of the Google APIs. We have no control over them.
