### ISSUE TITLE
Fix BEM class naming

### ISSUE THREAD

**Issue by izziaraffaele** [ubilabs/react-geosuggest#36]
The Block is "geosuggest" while items are "input", "suggests" and "suggest-item". 

So "geosuggest-item" here https://github.com/ubilabs/react-geosuggest/blob/master/src/GeosuggestItem.jsx should be changed to geosuggest__suggest-item 

The --focus modifier should be added and used instead of https://github.com/ubilabs/react-geosuggest/blob/master/src/geosuggest.css#L20

**Comment by ro-ka** [comment]
As this is not urgent, I would delay this until there is a breaking change for some other reason. Only breaking and releasing a new master version because of the classes doesn’t make much sense.

**Comment by aybmab** [comment]
Instead of using BEM, which seems to be dying and out of use, can we support the passing in of a styles object that maps expected class names to classnames provided by users?

**Comment by ro-ka** [comment]
That’s a nice idea, too. But still this would be a breaking change. As we don’t want to break, this is moved to a distant future date.
