### ISSUE TITLE
Fixtures: could we separate the label displayed, and a value (taken when clicking on a fixture?)

### ISSUE THREAD

**Issue by MaxInMoon** [ubilabs/react-geosuggest#363]
**Question / Enhancement**

I would like to display a fixture with a nickname (`label`), and use an other `value` for `click/request` action, like so:

Fixture item exemple:
```javascript 
{
  value: `${address.street} ${address.city}, ${address.zip} ${address.city}, ${address.country}`,
  label: `${address.name}`,
  lat: address.latitude,
  lng: address.longitude,
  className: 'addressFixture',
}

```

Thanks!

**Comment by ro-ka** [comment]
You get the suggest object when selected and can use any value in there, not just the label. Does this help?
