### ISSUE TITLE
option to exclude fixtures from suggestions list

### ISSUE THREAD

**Issue by praveen612** [ubilabs/react-geosuggest#371]
### Short description
If you don't want to include matched fixtures along with google's suggestions list currently there is no option for it. Sorry if I am missing obvious from the docs, could not make it work for my use case though.

### Expected results
Option to pass a property say `excludeFixtures`, making it true will not include matched fixtures with google suggestion when user enters his input

If this is already present or doesn't come under the scope of the component, feel free to close this issue.
If you feel this option can be included I am happy to send a PR for this.
Thank you for creating this component.

**Comment by praveen612** [comment]
hi @ro-ka please let me know your thoughts on this when you get time. Thanks :)

**Comment by yfr** [comment]
Thanks for the issue and the PR. 

Just a quick thought: Isn't it possible to use [skipSuggest[(https://github.com/ubilabs/react-geosuggest/blob/6e9448f594d259dd3afe66965d0c667126994404/README.md#skipsuggest) Prop for this? 

Let's say with an always true condition?

**Comment by praveen612** [comment]
making `skipSuggest` to return true always will not display any suggestions. Please correct me if I am wrong.

**Comment by yfr** [comment]
You are right. This might be a long shot and maybe not very practicable but it might remove the need for a new prop for a special case. 

You could use the `onChange` handler to store the current input value of Geosuggest in you parent component. Then you could use either `skipSuggest` or maybe even `renderSuggestItem` to check the input value and render items or leave them. Or you could just omit the suggest items to the Geosuggest component when there is an input value.

**Comment by praveen612** [comment]
yes, that works for my use case. Did not think in that direction!
Thanks for the suggestion. I will close the issue and the PR.
