### ISSUE TITLE
Persist Google API SDK object on first use instead of on mount

### ISSUE THREAD

**Issue by gbedardsiceupgrade** [ubilabs/react-geosuggest#379]
### Short description

Is there any reason why the SDK object is persisted on component mount instead of when only it's actually needed for the first time? This would allow use cases where the google maps api script is loaded dynamically after the app is mounted instead of being loaded statically before it's mounted.

If you're open to that change, I can open a quick PR.

**Comment by manelgarcia** [comment]
I'm also stuck with this problem. It would be perfect to fix it 🙂

Can't change library language or just load it dynamically.  😔

Did someone managed to achieve it?

Thanks!

**Comment by ro-ka** [comment]
Does this thread help you?
https://github.com/ubilabs/react-geosuggest/issues/130#issuecomment-278507213

**Comment by ro-ka** [comment]
Closing this because of lack of feedback. Reopen if needed.

**Comment by gbedardsiceupgrade** [comment]
Ah, sorry for the lack of feedback and thanks for the help. I have a similar workaround that just loads the google maps script on first mount before rendering the geosuggest component:

```
  componentDidMount() {
    const { loadApi } = this.props;

    // Consider the maps api loaded if no `loadApi` function is provided
    const loaded = (!!global.google && !!global.google.maps) || !loadApi;

    if (!loaded) {
      loadApi().then(() => {
        this.setState({ loaded: true });
      });
    }

    this.setState({
      loaded
    });
  }

  render() {
    const { loaded } = this.state;
    const { loadApi, ...props } = this.props;

    if (!loaded) {
      return null;
    }

    return <PlaceInput {...props} />;
  }
```

Would have been nice to have something like this built in, similar to how [react-google-recaptcha does it](https://github.com/dozoisch/react-google-recaptcha/blob/master/src/recaptcha-wrapper.js).
