### ISSUE TITLE
postal_code not received in onSuggestSelect

### ISSUE THREAD

**Issue by rambabusaravanan** [ubilabs/react-geosuggest#380]
### Short description

I was trying to get address components along with postal_code

### Expected results

I expected that search for an area and on selecting an item would give me all the address components as per the "Places Detail API", https://developers.google.com/places/web-service/details which includes postal_code

### Actual results

Since the library is using `Geocode Service`, "postal_code" is missing in maximum cases in its response.

Please make a way to include postal_code in `onSuggestSelect` callback.

**Comment by ro-ka** [comment]
The result from Google is passed through — if it’s not included there, we have no influence on this.
