### ISSUE TITLE
onBlur called but it should not

### ISSUE THREAD

**Issue by Titozzz** [ubilabs/react-geosuggest#384]
### My issue

I'm implementing react-geosuggest with react-final-form, but react-geosuggest has a default behavior that affects me : onBlur is called even if the input stays focused.

When I press ESC and the input is focus, it calls this code
```
hideSuggests = () => {
    this.props.onBlur(this.state.userInput);
    this.timer = setTimeout(() => {
      this.setState({
        isSuggestsHidden: true,
        activeSuggest: null
      });
    }, 100);
  };
```

but the input actually stays focus. I think the user should be allowed to do this (using onEscape) but it should definitely not be a default behavior.

**Comment by ro-ka** [comment]
You’re right, pressing `ESC` should blur the input. Wanna open a PR for this?

**Comment by plumdumpling** [comment]
The input should not lose focus when pressing the `ESC` key, but the `onBlur` should be only called when the input loses focus. I opened a pull request for this.
