### ISSUE TITLE
TDD with geosuggest

### ISSUE THREAD

**Issue by forrestblade** [ubilabs/react-geosuggest#390]
So I am currently running into some issues and could use some guidance concerning testing.  I'm not trying to test geosuggest specifically as the dev team has already done that. However I am running into the issue where google is coming back undefined in my test and I'm not sure how to resolve this.  Any help or references to projects that have tested components with geosuggest functionality would be greatly appreciated.

**Comment by sean-johnson** [comment]
I am having this issue also, I have ensured my API key is linked, and I am getting a 200 response from the google maps API meaning that authentication is ok, however I am getting `undefined` returned from onSuggestSelect(), anyone else getting this?
