### ISSUE TITLE
Google registered Trademark Issue 

### ISSUE THREAD

**Issue by nishant8BITS** [ubilabs/react-geosuggest#391]
I wanted to used react-geosuggest for my company project but when I see Note from googles regarding using Google Place Autocomplete without Google Map 

![screen shot 2018-07-19 at 17 58 56](https://user-images.githubusercontent.com/4658636/42954589-7220576e-8b7d-11e8-8033-d134320cc20d.png)

It's clearly mentioning that One should must include the **Powered by Google** logo. But when I tried demo http://ubilabs.github.io/react-geosuggest/ then I don't see 'Powered by Google' logo. If I use this react-geosuggest as it is without  **Powered by Google** will it cause any legal issue ?

**Comment by ro-ka** [comment]
Yes, *Powered by Google* has to be displayed somewhere — either via a map or close to the input. You can use CSS to add it to the list or display it next to the input. Does this help you?

**Comment by nishant8BITS** [comment]
Hi @ro-ka  Thanks for your reply.
