### ISSUE TITLE
Accessibility issue when click tab key

### ISSUE THREAD

**Issue by linzhaoken** [ubilabs/react-geosuggest#398]
### Short description

I am doing accessibility check on my site, I found when the geosuggest input is focused if I press tab key, it will trigger onSuggestSelect event which will cause update on site's content.

### Expected results

I expected that by using keyboard key tab on input field, it should not trigger and functional events.

### Actual results

The onSuggestSelect event is triggered when click tab key.

### Reproduction steps

1. Go to geosuggest input field
2. write console log in onKeyDown and onSuggestSelect event
3. Click on tab key from your keyboard
4. observe the browser console
5. You will see onSuggestSelect is called when press tab key.

**Comment by 12Noone** [comment]
Reporting this as a problem as well. We use this in a form with redux-forms and it's causing the value of the input field to be lost. is there anything we can do besides disabling TAB ? I'd like to keep the site accessible.

**Comment by gorkapit** [comment]
In fact is not a bug but a feature. It's explained in the docs: https://github.com/ubilabs/react-geosuggest#ignoretab

**Comment by linzhaoken** [comment]
@gorkapit thanks for the finding.

**Comment by linzhaoken** [comment]
Close this since it is a feature designed.
