### ISSUE TITLE
Point package.json main to built file

### ISSUE THREAD

**Issue by alistairjcbrown** [ubilabs/react-geosuggest#4]
It would be worth updating the `main` property in the `package.json` file to point to `dist/react-geosuggest.js` (or equivalent pure JS file if that's not suitable) so that using `require` to pull `react-geosuggest` doesn't first require a build step.

For me, as this component is JSX, I have to update my webpack config and jest preprocessor script to include `react-geosuggest` as an allowed `node_modules` library to be included as part of the build.

**Comment by ro-ka** [comment]
Thanks for the PR!

As I use JSX for all React stuff, this issue didn’t appear. Released as `1.2.2` on npm.
