### ISSUE TITLE
TypeError: Cannot read property 'AutocompleteService' of undefined     at Geosuggest.componentWillMount (Geosuggest.js:209)

### ISSUE THREAD

**Issue by kruyvanna** [ubilabs/react-geosuggest#400]
### Short description

I was trying to do use this library

### Expected results

Geosuggest render

### Actual results

I got error 
```
TypeError: Cannot read property 'AutocompleteService' of undefined     at Geosuggest.componentWillMount (Geosuggest.js:209)
```

### Reproduction steps

1. Import
2. Use compoonent

### Additional Information

```
Please copy/paste any additional information you would like to supply (error messages, screenshots, ...)
```

**Comment by ro-ka** [comment]
You need to add the Google Maps SDK to your side, including the places library. Add something like this to your `<head>`:

```html
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=YOUR_KEY"></script>
```

**Comment by kruyvanna** [comment]
my bad. much thanks

**Comment by raj360** [comment]
Greate thanks lad
