### ISSUE TITLE
No results on react 14/15 (geosuggest v2.9.0)

### ISSUE THREAD

**Issue by WindRider7** [ubilabs/react-geosuggest#405]
### Short description

I was trying to search for some addresses, but could not find any.

### Expected results

To see search results or error about my daily quota in console.

### Actual results

I don't see google search results (only fixtures).

### Reproduction steps

1. Use **react** (and **react-dom**) version **14** or **15**
2. Add **\<Geosuggest />** class and provide **API key**
3. Type some address in search box
4. See no results displayed

### Additional Information

I tested with **react** version **14** and **15** with _**react-geosuggest**_ **v2.9.0** I had no results.
I tried _**react-geosuggest**_ **v2.8.0** everything seem to be working.

Example: https://codesandbox.io/s/p5ym062qox

**Comment by schefpet** [comment]
We have the same problem.
