### ISSUE TITLE
Integrate with ARCGIS

### ISSUE THREAD

**Issue by ifeanyidavid** [ubilabs/react-geosuggest#412]
### Short description

Is it possible to make react-geosuggest work with [ARCGIS](https://developers.arcgis.com/labs/javascript/search-for-an-address/)

**Comment by ro-ka** [comment]
We would need to fork it or make it abstract in a way that it could be integrated with Bing, Mapbox, …

**Comment by ro-ka** [comment]
This is not planned currently, so I’m closing this.
