### ISSUE TITLE
Additionnal props to fixtures

### ISSUE THREAD

**Issue by jabidof** [ubilabs/react-geosuggest#413]
### Short description

Possibility to have custom props in the _fixtures_ that are available within the callbacks: onSuggestSelect, onActivateSuggest, etc.

### Expected results

```
onSuggestionSelect (suggestion) {
		const {map, maps} = this.state;
		if (!suggestion) {
			return;
		}
		if (!map || !maps) {
			return;
		}
		**_if (suggestion.myPropThatIWant) {
			// do something special based on the myPropThatIWant;
		}_**
		map.setCenter(new maps.LatLng(suggestion.location.lat, suggestion.location.lng))
		map.setZoom(16)
	}
```

I forgot to say the component is awesome and saved me many dev hours!

**Comment by ro-ka** [comment]
Thanks for the feedback!  🎉 

Feel free to tackle this and open a PR!

**Comment by atiqueansari1987** [comment]
@ro-ka I can pick it but I am a little confused, will you please explain the changes required?

**Comment by ro-ka** [comment]
You can now pass custom props with your fixtures thanks to #430.

@atiqueansari1987, sorry for my late response. Checkout the PR to see how it was done. Thanks for offering to tackle this!
