### ISSUE TITLE
Fixture selection

### ISSUE THREAD

**Issue by matejcreatix** [ubilabs/react-geosuggest#416]
### Short description

When I click on fixture item neither onChange nor onSuggestSelect are fired.

### Expected results

I suppose onChange should be fired

**Comment by matejcreatix** [comment]
it happens only when there is no location in a fixture

**Comment by ro-ka** [comment]
When there is no location for a fixture it should be geocoded — is there an error with the Geocoder? 

Can you provide a test page for the problem? I just tested the example with a fixture without a location and it worked.

**Comment by ro-ka** [comment]
Closing this because there is no feedback. Reopen if this problem still exists and provide an example.
