### ISSUE TITLE
Capture City, State, & ZipCode Values From Label

### ISSUE THREAD

**Issue by lopezdp** [ubilabs/react-geosuggest#417]
### Short description

I am trying to capture the City, State, & Zipcode value from the results provided by the `onSuggestSelect` prop.

### Expected results

I created a handler to process the changes returned by `onSuggestSelect` and in that handler I am trying to capture the data I need to persist it into `state`. Using the following:

```
handleOnSuggestSelect(suggestion) {
  this.setState({
    address: suggestion.label
  });
}
```

I **expected** that the `suggestion.label` value would store the entire address as such:
`1234 Maple Street, Miami, FL, 33010, USA`

### Actual results

Instead of `1234 Maple Street, Miami, FL, 33010, USA`, what I saw was that a value of: `1234 Maple Street, Street` showed up instead. Why does the value of `Street` show up after the initial street address?

### Additional Information

How do I get the different address components from the label? Especially the city, state, and zip code?

**Comment by ro-ka** [comment]
This is what Google returns from it’s API… We pass on the complete response, too. You can use that to get additional data.

Does this help you?
