### ISSUE TITLE
Reduce limit on autocomplete suggestions

### ISSUE THREAD

**Issue by andyrehab** [ubilabs/react-geosuggest#419]
### Short description

I would like to return only 3 suggestions on the autocomplete field.

### Expected results

I would like to return only 3 suggestions

### Actual results

I can't see any option to change the amount of results, I've tried maxFixtures but I'm always getting 5 suggestions on each search.

### Reproduction steps

4. Refresh the page and wait 5 secs
5. Finally the error will happen

### Additional Information

```
Please copy/paste any additional information you would like to supply (error messages, screenshots, ...)
```

**Comment by ro-ka** [comment]
The Google API doesn’t provide this parameter. Please check the [docs here](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest).

The `maxFixtures` prop is there to limit the rendering of the fixtures (aka the places you pass into the component) and has nothing to do with what Google is returning.
