### ISSUE TITLE
Selecting "Texas, USA" from google maps address components only returns country 'US'

### ISSUE THREAD

**Issue by ilyaGurevich** [ubilabs/react-geosuggest#421]
### Short description

Searching for 'Texas, USA' returns only 'US' as an address component from google maps

### Expected results

I expected to find the short or long name of the state of 'Texas' or 'TX' in the address_components but it was not there. 

### Reproduction steps

1. Search for Texas, USA
2. Select Texas, USA from dropdown
3. Search in address_components from the event
4. Address_components will only show 'US' country with no state component. 

### Disclaimer
Could be an issue with google maps api and not react-geosuggest

**Comment by ro-ka** [comment]
That part is directly returned from the Google API, this component has no influence on that.

**Comment by ilyaGurevich** [comment]
@ro-ka looks like it was a temporary issue with geocoding api as it works properly now.

Thanks
