### ISSUE TITLE
placeDetailField is not working without geometry field.

### ISSUE THREAD

**Issue by neomaxzero** [ubilabs/react-geosuggest#422]
### Short description

When using `placeDetailField` property and error is thrown.

### Expected results

I was trying to define `placeDetailField` with only this field : `['address_components']`.

### Actual results

Instead of retrieving only what I stated. An error was thrown by the internals.

### Reproduction steps

1. Create a react-geosuggest like this snippet:
```
<Geosuggest
          placeDetailFields={['address_components']}
          onSuggestSelect={this.onSuggestSelect}
/>
```
2.  Select an option.
3. Check the error in the console.

### Additional Information

Looks like we rely on the 'geometry' field to return the selected location. With a little bit of guidance I can make a PR to fix it.

**Comment by ro-ka** [comment]
You’re right, thats needed. Feel free to open a PR! What do you need to get started?

**Comment by neomaxzero** [comment]
My first thought was to merge the fields stated in `placeDetailFields` with `['geometry']`. Is that something that makes sense to you?

**Comment by ro-ka** [comment]
Sorry, totally missed your response! I’m sorry. Had some time to tackle the dependencies and got onto this problem again as the types for Google Maps got updated with this behaviour. Will be merged when it got reviewed.
