### ISSUE TITLE
how to set the values manually in input box

### ISSUE THREAD

**Issue by SabikeRaja** [ubilabs/react-geosuggest#424]
### Short description

While search the address it display the address description. I want to split the description and set the first spited value. 

### Expected results

I have to set the input value after split the description.

### Actual results

When i set the spited value using initial-value props from geosuggest it show full description and after some sec it shows the spited value

**Comment by SabikeRaja** [comment]
Any update on this one ??

**Comment by ro-ka** [comment]
Hi! Is [`getSuggestLabel`](https://github.com/ubilabs/react-geosuggest#getsuggestlabel) what you’re looking for?

**Comment by ro-ka** [comment]
Closing this because there is no feedback. Reopen if this problem still exists and provide an example.
