### ISSUE TITLE
Optional sessionTokens?

### ISSUE THREAD

**Issue by DavidHughes** [ubilabs/react-geosuggest#425]
Hi,

#393 introduced the usage of sessionTokens to all Google Maps requests. I was in the middle of upgrading our geosuggest installation to a version with this PR merged but a colleague pointed out that based on Google's [pricing sheet](https://cloud.google.com/maps-platform/pricing/sheet/?_ga=2.34314407.78710768.1550142096-86830810.1548158473), the upgrade could in our case end up with an increased billing. See also this section of [Google's consumption optimization guide](https://developers.google.com/maps/optimization-guide#places) which suggests that there are use-cases where request-based billing is potentially optimal.

What do people think? How has #393 impacted your bills?

Thanks!

**Comment by ro-ka** [comment]
Hi! #393 was just a tooling upgrade and change to TypeScript. sessionTokens got introduced with #394. Using sessionTokens should reduce your bill as will the usage of the `placeDetailFields` prop. Did you see any pricing changes?

**Comment by uanjoze** [comment]
Hi guys! First of all, thanks a lot for this package!
I'm trying to use session tokens but this implementation seems to not be working. Every key stroke generates a new token for each request (which misses the point) and the attached URL parameter is `token` instead of `sessionToken`.
If I work out a way of doing it myself and I don't get too lost with Typescript I can try to create a pull request.

**Comment by stephane-klein** [comment]
@uanjoze where do you see that geosuggest must use `sessionToken` instead `token`? Where in documentation?

**Comment by uanjoze** [comment]
Places API documentation
https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteSessionToken

Also when they introduced the pricing changes
https://cloud.google.com/maps-platform/user-guide/pricing-changes/

In the example for the query here it's all lowercased, tho
https://developers.google.com/places/web-service/usage-and-billing#ac-with-details-session

**Comment by SputnikTee** [comment]
@uanjoze are there any new developments regarding this issue?
We experience an unexpected high "Places Details" bill and having a strong guess that it is related to the autocomplete requests and session tokens. 
I didn't look at the geosuggest code yet, but while testing I noticed that every autocomplete request has a different token.

**Comment by uanjoze** [comment]
Hey @SputnikTee, currently TypeScript stops me from trying to implement it on this package, so I stopped using it. I'm now using sessionTokens are you can see the requests reflected in Google Billing.

If you see a "token" added to the query, ignore, as this is NOT a sessionToken. This is a token generated by the Google library (for Google use). The sessionToken, when used, is encoded and attached to the API request (so you'll never see the words "sessionToken" in the URL)

**Comment by ro-ka** [comment]
@uanjoze is right, the `sessionToken` string never appears in the URL. `token` is something different, I don’t know why Google is adding this. Maybe to verify the callback calls?

You can check that `sessionToken` works as expected by logging it out after it gets created and then check the API requests, looking for that token string. Note that Google prefixes the token with `20s` and passes it as a GET key to their API server. Check the Requests log and the console.log of the sessionToken.

Here is a screen of my log:

![Bildschirmfoto 2020-05-29 um 09 17 40](https://user-images.githubusercontent.com/840022/83232723-e86ade80-a18d-11ea-9f70-7cab71e6975c.jpg)
