### ISSUE TITLE
Suggest list doesn't support keyboard input

### ISSUE THREAD

**Issue by andrewdushane** [ubilabs/react-geosuggest#426]
### Short description

Suggest list doesn't support keyboard input

### Expected results

When the suggest list is open, suggests can only be selected by click/press. It would improve accessibility/usability to enable arrow navigation of suggests with Enter to select one (like a native browser select).

Wondering if the maintainers would be open to adding this functionality and if there are any possible issues I haven't considered.

**Comment by ro-ka** [comment]
Can you create a test setup where it doesn’t work? Or list what browser you use?

Going to http://ubilabs.github.io/react-geosuggest/ and using the keyboard works as expected for me.

**Comment by andrewdushane** [comment]
Interesting! Doesn't work in the what I was looking at and I assumed it wasn't supported. Must be an app issue. Thanks.

**Comment by ro-ka** [comment]
Hope you find out what’s the problem. All the best!
