### ISSUE TITLE
Getting places photos?

### ISSUE THREAD

**Issue by mckeever02** [ubilabs/react-geosuggest#429]
Great library! I'm wondering if it's possible to retrieve photos of the response using this wrapper?  I understand that some places return a photos object:

```
"photos": [
      {
        "height": 3024,
        "html_attributions": [
          "<a href=\"https://maps.google.com/maps/contrib/105108433893792866137/photos\">Verneri Pohjola</a>"
        ],
        "width": 4032
      },
]
```

Is there a way to actually get the photo from this?

**Comment by ro-ka** [comment]
Glad you like this component!

It’s out of the scope of geosuggest, but here is what I found: You get either a [GeocoderResult](https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderResult) or a [PlaceResult](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult) in a suggest. Check the Google docs to get the photos for the found `placeId`. As I understand it, the `PlaceResult` has a method to get the photo url and with a `GeocoderResult` you’ll need to query the Places API first.

Good luck!
