### ISSUE TITLE
How to use google map Api strictbound options in react geosuggest?

### ISSUE THREAD

**Issue by navaswd** [ubilabs/react-geosuggest#435]
### Short description

I was trying to do display the list of address based on entered Zipcode.

### Expected results

I expected that display only the exact result what I searched for.

### Actual results

Instead of  that i am getting unwanted result from out of the region.

code below:
` <Geosuggest
                                  //fixtures={fixtures}
                                  onFocus={this.onFocus}
                                  onBlur={this.onBlur}
                                  onChange={this.onChanges}
                                  onSuggestSelect={this.onSuggestSelect}
                                  onSuggestNoResults={this.onSuggestNoResults}
                                  country="USA"
                                  location={this.state.location}
                                  radius="100"
                                  highlightMatch={true}
                                />`

**Comment by ro-ka** [comment]
The bounds / radius are a bias, not a limit. Also, this is behaviour from the Google Maps API and not in the control of this component.
