### ISSUE TITLE
Use with Material UI

### ISSUE THREAD

**Issue by weber93** [ubilabs/react-geosuggest#437]
I did find [this](https://stackoverflow.com/questions/45880795/react-geosuggest-with-material-ui) and [this](https://github.com/ubilabs/react-geosuggest/issues/79) in my search before posting from a few years ago.

I am using [Material-UI v4](https://material-ui.com/) in my project and would like to make the styling match for this input component. I can just try to make the CSS match (though it is no small task). I was wondering how possible it would be to:

1. Add Support for MUI since this is a very widely used Component Library (I know how unlikely this is but hey, can't blame me for trying). 

2. For me to somehow replace Geosuggest's input with MUI's?

If not I guess the CSS route will work but this means potential issues anytime MUI updates there CSS, as well as having to replicate the animations. 

I currently use [this package](https://github.com/hibiken/react-places-autocomplete) but the outputs are not structured very well and I much prefer the way your's does (parsing the address_components array).

Thank you! 

![image](https://user-images.githubusercontent.com/18507767/59201816-e5cc3f00-8b60-11e9-82f7-2374546a7279.png)

**Comment by ro-ka** [comment]
Discussion of this in #447.
