### ISSUE TITLE
Remove usage of `componentWillReceiveProps` and `componentWillMount` for React 17

### ISSUE THREAD

**Issue by gbedardsiceupgrade** [ubilabs/react-geosuggest#439]
### Short description
`componentWillReceiveProps` and `componentWillMount` both trigger warnings in `react@16.9.x`, and won't be supported in `react@17.x.x`.

### Expected results
We should either remove these and migrate to `componentDidUpdate` and `componentDidMount` or rename them with the `UNSAFE_` prefix.

**Comment by pheeria** [comment]
Faced here: #444

**Comment by gbedardsiceupgrade** [comment]
Thanks! Closing this one.
