### ISSUE TITLE
Add type="search" option to input

### ISSUE THREAD

**Issue by csandman** [ubilabs/react-geosuggest#441]
### Short description

Add the option to set the input field to type="search"

### Expected results

It would be great to be able to set the input field to the "search" type in order to have the clear option available.  This should be super simple unless it interferes with anything else.

### Actual results

Currently this is not an option in this utility

### Additional Information

Here is an example of what it might look like:

![download (3)](https://user-images.githubusercontent.com/9214195/64735030-bb6a8480-d4b5-11e9-98bc-c02d6aa28bcc.png)

the property could be:

#### inputType
Type: `String`
Default: `text`

Options are `text` and `search`.  Set to `search` if you would like to have a clear button on the end of your input.

*or*

#### searchTypeInput
Type: `Boolean`
Default: `false`

Set to `true` if you would like to change the input field to type="search" and have a clear button on the end of your input.

**Comment by ro-ka** [comment]
I’m against that as the only difference currently is a magnifier instead of an enter key on mobile phones. That could be misleading though, as you won’t neccessarily start a search by pressing it. You search by typing and an enter key to select and proceed to the next field is more fitting.

In short: It is an autocomplete, not a search.

**Comment by ArditGashi** [comment]
It is what people want it to be? Why would you not make an HTML input not have other types? It makes no sense. Please reconsider adding search type even though you don't like it - we do.

**Comment by csandman** [comment]
I checked and this is true for Android phones only, it does change to a magnifying glass.  But the more common change across devices is the clear button that is added at the end of the input field which is really a feature that would be useful for this component.  At the end of the day, it is still a search of Google Places.

And if you don't like having it added by default, you could always go for my original suggestion which was to add a prop for it, leaving it as `type="text"` by default, it would be really nice to have this option as there is no way to add this feature otherwise.

If you don't want to do this yourself, I could always submit a PR with it!
