### ISSUE TITLE
In a list of instances scenario identify index of the instance

### ISSUE THREAD

**Issue by mnkcoder** [ubilabs/react-geosuggest#442]
### Short description

I have an array of events scenario, each event has a location for which I am using this library to capture the geo location. However, I am wondering how to identify which index of geo suggest instance needs to be updated.

Unless I am missing something, I think it would be helpful to return index of the instance during **onSuggestSelect**?

**Comment by ro-ka** [comment]
You should handle that by yourself in your application like this:

```tsx
[1,2,3].forEach(instanceId => (
    <Geosuggest
      onSuggestSelect={(suggest) => handleSuggestSelect(instanceId, suggest)}
      location={new google.maps.LatLng(53.558572, 9.9278215)}
      radius="20"
    />
));
```
