### ISSUE TITLE
How do I mock this input for testing?

### ISSUE THREAD

**Issue by lipe-dev** [ubilabs/react-geosuggest#446]
### Short description

I want to mock this input during a test and interact with it and select a place. I need this because I'm writing tests for a form that uses this input.

### Expected results

I wanted a way to mock the google API results so during my test after changing the text inside the text input a list of mocked places would show up, and I would be able to simulate a click on one of them and get a mock location.

### Actual results

There seem to be no ways to do any of this besides changing the input text value.

### Additional Information

I managed to mock enough of the Google maps api to make the input appear on screen, but I don't know which functions I need to mock to get some fake results for testing purposes.

We use @testing-library/react, so we can't mess with the state directly, so I'm currently unable to test any forms that include a location picker :(

**Comment by lipe-dev** [comment]
Turns out you had a complete googleStub in the tests folder...
I added that to my test and tried replicating the selecting you did on your tests, type "New", arrow down, enter... but it's not working, and I'm not sure if I'm completely missing the mark here :(

**Comment by ro-ka** [comment]
I guess this depends on your testing framework. This component uses the `autocompleteService.getPlacePredictions`, `placesService.getDetails` and `geocoder.geocode` for user input that isn’t a place prediction. You should mock them all to get this working.
