### ISSUE TITLE
Add support for additional types

### ISSUE THREAD

**Issue by belhassen07** [ubilabs/react-geosuggest#448]
I was trying to add "airport" type using types but since there are only 4 supported types, I obviously can't. any ideas on how should I do that? 

Do you intend to support other types?

**Comment by ro-ka** [comment]
We pass everything you define in `types` directly to the Google API. Check the [reference](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest.types) for what is allowed. They state that you can just pass one type at a time.

The places details seem to get those various types, but the API for place autocomplete requests only allows a few, sadly. Check https://developers.google.com/places/supported_types#table3 for further information.
