### ISSUE TITLE
 Line 4:3:  'handleSubmit' is not defined  no-undef

### ISSUE THREAD

**Issue by ghost** [ubilabs/react-geosuggest#449]
import React from "react";

const Loginform = () => {
  handleSubmit = event => {
    event.preventDefault();  
}

  return (
    <div >
       <h1 className="form-tagline">Catch Of The Day</h1>
       <form onsubmit={this.handleSubmit}>
           <h1 className="header">Login Form</h1>
           <div className="email">
           <input type="text" placeholder=" Your Email address" className="email-box" ></input>
           </div>
           <div className="password">
           <input type="password" placeholder="password" className="pass-box"></input> 
           </div>
           <div className="forget-pass">
           <p href="#">Forget password</p>
           </div>
           <div className="submit">
           <button type="submit" placeholder="password" className="submit-buton">Submit</button> 
           </div>
           <div className="forget-pass">
           <p href="#">Not Resgistered yet, Resgistered Now</p>
           </div>
       </form>
    </div>
  );
}
export default Loginform;
why give error that handleSubmit is not define . please help me

**Comment by ro-ka** [comment]
This has nothing to do with this library, but it seems like you miss a `const` in front of `handleSubmit`.
