### ISSUE TITLE
Add inputId prop

### ISSUE THREAD

**Issue by lucasmedeiros** [ubilabs/react-geosuggest#450]
### Short description

I was trying to add a label for the suggest input, but it didn't have the expected behaviour (input focus on label click), because I couldn't set the input ID. Placeholder is fine, but in some cases I'd rather use label for better UX.

It can be implemented by adding a simple `inputId` prop option.

**Comment by ro-ka** [comment]
Modified the `id` prop so that it will be added to the input, too. You can get a label by providing the `label` and `id` props already.
