### ISSUE TITLE
Prop `aria-owns` did not match.  - SSR

### ISSUE THREAD

**Issue by HPieters** [ubilabs/react-geosuggest#452]
### Short description

I was trying to add react-geosuggest (v2.12.1) to a next.js (v9.1) application, however, I get a warning in my console: `Warning: Prop `aria-owns` did not match. Server: "geosuggest__list_c2f6f86958fd7" Client: "geosuggest__list_b47ff6fa5019f"` 

### Expected results

I expected the integration to work without warnings.

### Actual results

I got a warning in the console, the culprit, in my opinion, is math.random generated listId in the Geosuggest.tsx.

https://github.com/ubilabs/react-geosuggest/blob/9f8fabbb6a066f004bd98490c79e229c9130d8ed/src/Geosuggest.tsx#L108
### Additional Information

Perhaps I am simply missing something here or the warning might not be relevant at all, however, I like to keep my console clean and wasn't able to solve this on my own.

**Comment by cojj90** [comment]
I can't get snapshot test passing because of this xD

**Comment by cojj90** [comment]
I can't get snapshot testing passing because of this xD reverting to `2.12.0`

**Comment by ro-ka** [comment]
We’ll take a look into this.

**Comment by ro-ka** [comment]
The random ID will be removed and it’s possible to set an ID on the Geosuggest to have aria-owns work even when there are multiple instances on a page. Thanks for reporting!

**Comment by adamklepacz** [comment]
@ro-ka 

It seems it is still not fixed. I'm having the same issue in next.js application:

![SearchInput jsx — newst-storefront-fe-repo 2020-06-03 15-21-02](https://user-images.githubusercontent.com/27632432/83641497-ea79d680-a5ad-11ea-85b1-65c777c07d1a.png)
![localhost:3001 2020-06-03 15-21-11](https://user-images.githubusercontent.com/27632432/83641502-ebab0380-a5ad-11ea-9e56-b4edb3698fc9.png)

**Comment by ro-ka** [comment]
A release was due, the PR was just released in `2.13.1`.
