### ISSUE TITLE
Radius not working

### ISSUE THREAD

**Issue by Alin13** [ubilabs/react-geosuggest#454]
### Short description
Radius & location configs are not working.

### Expected results
Radius + location should work

### Actual results
I get results from all country.

### Additional Information
This is the minimal setup:
```
<Geosuggest
      country="ro"
      types={['address']}
      location={new window.google.maps.LatLng(45.86625739999999, 22.9143737)}
      radius={50000}
 />
```

Also tried using radius as string (as in your examples), but it's still not working. Am I missing something ?

Thank you for your time :)

**Comment by ro-ka** [comment]
We pass on the radius to the Google Places Autocomplete API. It doesn’t matter whether this is a string or number. According to [their docs](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest.radius), the radius is just a bias and not a filter:

> The radius of the area used for prediction biasing. The radius is specified in meters, and must always be accompanied by a location property. Alternatively, bounds can be used.

So you should see that the first results are near your location and then there are results for other regions.

Does this answer your question? If not, reopen!
