### ISSUE TITLE
Billing issues

### ISSUE THREAD

**Issue by Alin13** [ubilabs/react-geosuggest#463]
Hello,

I have some questions regarding the configuration of the autocomplete that may impact the billing of Google services.

### Short description

 From the docs I understand that the only prop that has impact on the billing is **placeDetailFields**.

My configuration for **PlaceDetailFields** is: 
`placeDetailFields={['geometry.location']}` - I only use the latitude, longitude and the street name

The **geometry** fields should be in the **basic data SKU** ( https://developers.google.com/places/web-service/usage-and-billing#basic-data ):
![image](https://user-images.githubusercontent.com/35230931/82765613-039dbd00-9e21-11ea-9dbd-32b5a92ffaf6.png)

### Expected results

The billing amount should be 0$ (or much smaller than it actually is) - it should use the **Basic data SKU**

### Actual results

The billing amount is too big - it uses the **Places details SKU** and the **Autocomplete without places details - per session SKU**

![image](https://user-images.githubusercontent.com/35230931/82784960-4d5ec580-9e6a-11ea-99fb-0abf82e2f24a.png)

I don't understand why it is using the places details and I don't think this is correct. Is there something that I misunderstood / misused? Is there a way to reduce the costs?

Thank you for your time!

**Comment by jalanga** [comment]
+1

**Comment by ro-ka** [comment]
I just checked this: We are always adding `geometry` to the placeDetailFields when any are passed in. So passing in nothing returns all the values.

Adding anything else (e.g. `formatted_address`, `geometry` or `geometry.location`) just returns what expected: the geometry and what got specified.

Can you check your request in the browser console? This is the result when I copied your `placeDetailFields={['geometry.location']}` to the example app:
![Bildschirmfoto 2020-05-29 um 09 42 31](https://user-images.githubusercontent.com/840022/83234530-ba3ace00-a190-11ea-9ef2-44b97b9cd62a.png)

**Comment by Alin13** [comment]
My response is exactly the same as yours. Maybe I just didn't understand the pricing and why it uses 17$ and I was confused by the 0$ basic data.

Thanks for your response.
