### ISSUE TITLE
selectSuggest doesn't trigger onSelectSuggests 

### ISSUE THREAD

**Issue by fabiomangano93** [ubilabs/react-geosuggest#469]
### Short description

I wrote this simple [example](https://codesandbox.io/s/nostalgic-moser-rvmfv?file=/src/App.js.) to try this library.

![Screenshot 2020-06-12 at 16 36 37](https://user-images.githubusercontent.com/63911405/84514218-f448bb80-acca-11ea-8925-09584fce10a1.png)

### Expected results

I expected that, after updating the input value (via update function), when selectSuggest function is called, it triggers onSelectSuggest function.

Should it work like this ?

**Comment by ro-ka** [comment]
I should work like this. Bugfix is on its way, thanks for reporting!

**Comment by fabiomangano93** [comment]
Thank you !

**Comment by ro-ka** [comment]
Closed by #470
