### ISSUE TITLE
Inconsitent suggest.gmaps property received in onSuggestSelect

### ISSUE THREAD

**Issue by lytvynenkosv** [ubilabs/react-geosuggest#472]
### Short description

After upgrading to 2.14.0 I'm getting wrong type of `suggest.gmaps` in `onSuggestSelect` callback. 

### Expected results

Per documentation `suggest.gmaps` should be `google.maps.GeocoderResult` instance. 

### Actual results

After upgrading from 2.7.0 to 2.14.0 `suggest.gmaps` is `google.maps.places.PlaceResult` instance which is slightly different from `google.maps.GeocoderResult`. In my case important difference is absence of `gmaps.geometry.bounds` which I was using to filter objects by location.

### Additional Information

As far as i can see behavior most likely changed by this commit https://github.com/ubilabs/react-geosuggest/commit/68c8817ad64524fcde73d8f64e52ee8e9d566f21 It changed `geocodeSuggest` method logic so it use either Geocoder or Places API, as result this method will return either `google.maps.places.PlaceResult` or `google.maps.GeocoderResult`

Docs on both interfaces:

https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderResult

https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult

**Comment by lytvynenkosv** [comment]
Further investigation lead me to discussion under this PR https://github.com/ubilabs/react-geosuggest/pull/399 So looks like Places API is added on purpose to reduce cost. So i wonder if docs should be updated or there should be way to control geocoding logic.

**Comment by ro-ka** [comment]
You’re right that the Places API is used to reduce costs. We’re getting the result for free when doing PlaceSuggestion requests before.

If you rely on the bounds, you can get those from a `google.maps.places.PlaceResult`, too: `place.geometry.viewport` is a `google.maps.LatLngBounds` class.

Does this help you? Reopen if not!
