### ISSUE TITLE
Test `react-geosuggest` with puppeteer

### ISSUE THREAD

**Issue by Its-Alex** [ubilabs/react-geosuggest#475]
### Short description

Hi,

I was trying to test `react-geosuggest` in end2end tests with puppeteer. I would like to know if there is some way to identify when `react-geosuggest` is *loading* and when suggest has been *loaded*?

My problem is that I want to wait for `react-geosuggest` to find for suggestions before selecting one.

Thanks

**Comment by ro-ka** [comment]
Hi! You can check whether Google Maps loaded and then you check like any other React component…
