### ISSUE TITLE
utc_offset is deprecated as of November 2019 and will beturned off in November 2020. Use utc_offset_minutes instead.

### ISSUE THREAD

**Issue by FriendlyUser** [ubilabs/react-geosuggest#476]
### Short description

I am using react-geosuggest and getting a console warning. I am using react-geosuggest 0.2.14

### Expected results

I expected that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual results

utc_offset is deprecated as of November 2019 and will beturned off in November 2020. Use utc_offset_minutes instead. in my chrome console

### Reproduction steps

4. Refresh the page and wait 5 secs
5. Finally the error will happen

### Additional Information

```
Please copy/paste any additional information you would like to supply (error messages, screenshots, ...)
```

https://developers.google.com/maps/documentation/javascript/place_field_js_migration

**Comment by FriendlyUser** [comment]
https://stackoverflow.com/questions/59716825/google-maps-api-deprecation-error-in-vuejs-web-app-utc-offset-is-deprecated-as

Any updates on this?

**Comment by ro-ka** [comment]
Hi! This component isn’t using `utc_offset` anywhere… Check yourself: https://github.com/ubilabs/react-geosuggest/search?q=utc_offset Did you specify this anywhere?

Reopen if it turns out that this component is using it.

**Comment by FriendlyUser** [comment]
Thanks, it must be a different component.
