### ISSUE TITLE
ul role=listbox should define an aria-label or aria-labelledby

### ISSUE THREAD

**Issue by fcabreraupgrade** [ubilabs/react-geosuggest#478]
### Short description

I couldn't define aria-label / aria-labelledby on the item with `role=listbox`.

For an example of listbox behavior I'm following [this example](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html).

As an extra I found defining an accessible name is required for role=listbox [aria-docs](https://www.w3.org/TR/wai-aria-1.1/#listbox).

### Expected results

We should be able to define props for the element with `role=listbox`.

### Impacted code

https://github.com/ubilabs/react-geosuggest/blob/master/src/suggest-list.tsx#L70-L74

**Comment by Borrisson** [comment]
Also to add to this issue. 

if an initialValue is passed, the <ul> has no <li role="option"> child. If possible either make a conditional where if there are no <li> to list then do not render the ul element. 

`<div class="geosuggest__suggests-wrapper"><ul class="geosuggest__suggests geosuggest__suggests--hidden" role="listbox" id="geosuggest__list"></ul></div>`
