### ISSUE TITLE
Selecting an suggested item using Enter submits the form

### ISSUE THREAD

**Issue by janmyler** [ubilabs/react-geosuggest#49]
When the component lives in a form and one of the suggested items is selected using keyboard (arrows + hitting enter), the form is submitted.

From the source code I see you didn't include `event.preventDefault()` probably on purpose? Could this be at least configurable by props? There's no other way how to prevent this as you don't pass the event to the `onSuggestSelect` method.

**Comment by ro-ka** [comment]
Does it make sense to prevent always? Is it a use case to submit on select via enter? Sounds more like a bug, because it does not submit on other select modes (e.g. click) which is inconsistent.

**Comment by ro-ka** [comment]
Released with `1.10.0`. Thanks for reporting!

**Comment by janmyler** [comment]
@ro-ka, thanks for a quick fix!
