### ISSUE TITLE
'Avnei Hefetz' is an israli settlement city which is not coming in country 'IL' suggestions whereas 'Einav' is also an israli settlement city which is coming in country 'IL'  suggestions.

### ISSUE THREAD

**Issue by AishwaryaJayakumar** [ubilabs/react-geosuggest#492]
### Short description

I was trying to do search location using react-geosuggest based on type cities. I need to list out the cities in Israel where The city 'Avnei Hefetz' is an israli settlement city and it is not coming in suggestion drop down whereas 'Einav' is also an israli settlement city which is coming in search drop-down suggestions.

### Expected results

I need 'Avnei Hefetz' in search drop-down suggestions under country 'IL' (Israel) Is there any possible way?

### Actual results

Avnei Hefetz is not listed in search drop-downs.

**Comment by plumdumpling** [comment]
The suggestions are coming from the [Google API](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service). react-geosuggest has no influence on that.
