### ISSUE TITLE
Add component tests

### ISSUE THREAD

**Issue by skw** [ubilabs/react-geosuggest#53]
It would be great if this component had tests, and code coverage metrics. We can use `mocha`, `sinon`, `jsdom`, `proxyquire` and `testUtils`.

Thoughts?

**Comment by ro-ka** [comment]
Tests would indeed be great! I know, it’s a shame that there aren’t any yet…

**Comment by skw** [comment]
Okay cool, I'll try and set some up when I have a chance.

**Comment by ro-ka** [comment]
That would be fantastic! :)
