### ISSUE TITLE
call clean() outside Geosuggest section

### ISSUE THREAD

**Issue by farrrr** [ubilabs/react-geosuggest#54]
I have a button to clean form input value include geosuggest.

How to call clean() outside geosuggest section?

**Comment by Driklyn** [comment]
I'm no React expert, but I'm using `ref` for this purpose, like so:

```javascript
var App = React.createClass({
  render: function() {
    return (
      <div>
        <Geosuggest
          ref="geosuggest" />
      </div>
    );
  }

  clearSearch: function() {
    this.refs.geosuggest.clear();
  }
}
```

**Comment by ro-ka** [comment]
Does this help, @farrrr? Thanks, @Driklyn!

**Comment by ro-ka** [comment]
I suppose it is working, reopen if not!

**Comment by BesatZardosht** [comment]
I have same issue. I want to clear the input when I render the component. How can I do that?

**Comment by ro-ka** [comment]
Do you want to clear it on the first render? Then just provide an empty `initialValue`.
Do you want to clear it on every render call? Wouldn’t advice that…

You can call the clear like @Driklyn described above.

**Comment by BesatZardosht** [comment]
initialValue is not what I need. I neetd to clear it outside the component like, in its parent render. or by clicking a button.

**Comment by ro-ka** [comment]
I cannot say what the problem is without any code. However, this is not related to the component, it’s general React.
Did you check with the mentioned advises in you component?

**Comment by yfr** [comment]
When adding this method to geosuggest (just quick and dirty test). We are able to get the current `activeSuggest`. But after that the suggestion list collapses and `activeSugggest` is reset. 

This is a good thing as we do not want to have an `activeSuggest` when the list is not visible.

```
  selectActiveSuggest() {
    return this.state.activeSuggest;
  }

```

One solution would be that we have an exposed method to trigger geocodeSuggest return the response.

**Comment by michalica** [comment]
I am not sure but how can I call clear() on Focus when I use ES6 syntax?
