### ISSUE TITLE
Best way to initialize component with existing data?

### ISSUE THREAD

**Issue by joshgeller** [ubilabs/react-geosuggest#58]
Hello, great component, thanks for your hard work!

Lets say I save the suggest object returned by `onSuggestSelect`.

Can I feed this object back into a certain prop to re-create the previous state?

**Comment by ro-ka** [comment]
You can provide an `initialValue` and you can provide `fixtures`. Do these help? What do you want to achieve?

**Comment by joshgeller** [comment]
Thanks, that's what I am doing now. I guess I just want to make sure that if I am serializing/deserializing forms that include react-geosuggest, the component is being initialized to its previous state properly when data is loaded in.

**Comment by ro-ka** [comment]
Did you solve this for you?
