### ISSUE TITLE
reactify

### ISSUE THREAD

**Issue by zallek** [ubilabs/react-geosuggest#6]
Hi,

Great job you've done there. Thanks.
Just one question: why `reactify` is in `dependencies` and not `devDependencies` ?

**Comment by ro-ka** [comment]
Good question! Will move to `devDependencies`.

**Comment by ro-ka** [comment]
Released as `1.2.3`.

**Comment by idolize** [comment]
This change causes any builds that use Browserify and have this library as a dependency to now break. See #11.

**Comment by ro-ka** [comment]
Changed the build system and there is now reactify or similar anymore. Released as `1.4.0`
