### ISSUE TITLE
Item selection seems to be broken sometimes

### ISSUE THREAD

**Issue by janmyler** [ubilabs/react-geosuggest#60]
We had a bug reported of a user not being able to select an item from the suggestions.

I traced the problem to `GeosuggestItem.onClick` and `Geosuggest.hideSuggests` functions. There's a 100ms timeout before the state in `Geosuggest` component changes to hide the suggestions. If user clicks on a `GeosuggestItem`, the `hideSuggests` function is executed at the same time (on blur). If user doesn't release the mouse button to actually trigger a click event, the list of suggestions is gone and nothing has been selected.

What would be the most correct solution to this problem? Increasing the timeout interval in `hideSuggests` or simply using `onMouseDown` event in the `GeosuggestItem` instead?

**Comment by ro-ka** [comment]
I think mousedown could be solution, but then a user cannot “abort” a select by moving the clicked mouse away. Any ideas?
