### ISSUE TITLE
issue with assets/webpack (react best practices)

### ISSUE THREAD

**Issue by Bogdaan** [ubilabs/react-geosuggest#62]
In current release we unable to apply styles from variable.
For standart "webpack way" we requires styles as module and apply to element. For example:

   import myCss from './mycss-or-less-or-scss-or-other'
   ....
   <div className={myCss['css-selector']}></div>

And now i need apply my styles to element, but i cannot do that:

+ https://github.com/ubilabs/react-geosuggest/blob/master/src/Geosuggest.jsx#L384
+ https://github.com/ubilabs/react-geosuggest/blob/master/src/GeosuggestItem.jsx#L48
+ and other hardcoded styles

For example [ReactCSSTransitionGroup](http://facebook.github.io/react/docs/animation.html)
accept class names as parameter

**Comment by ro-ka** [comment]
I am not firm with webpack – what additions would be needed to make it work?

**Comment by Bogdaan** [comment]
class names of elements must accepted from props, in order to have custom styles for custom elements and load component with css-modules.
For example: https://github.com/Bogdaan/react-geosuggest/commit/02fedbdf02aec603831b81379c12e4880a16bf09

**Comment by ro-ka** [comment]
In the meantime we use webpack in a project, too, together with react-geosuggest and it is running fine.
I still don’t understand why the classes need to be replaced. Can you explain?

**Comment by Bogdaan** [comment]
@ro-ka i dont use "global-css". i use css-loader (rtfm "css modules") and load only critical-path css on page

**Comment by ro-ka** [comment]
I’m sorry, but I’m not into CSS modules and lack time to “rtfm”.
Are the needed changes to make it work in the commit you linked?

**Comment by ro-ka** [comment]
Reopen with more information.
