### ISSUE TITLE
The 'gmaps' object has functions instead of values (e.g. Lat/Lng)

### ISSUE THREAD

**Issue by amireldor** [ubilabs/react-geosuggest#63]
Hi. I want to use the complete gmaps object as returned by the Google Maps API after I select a location. The other values are not enough for what I'm trying to do. The problem I'm facing is that the gmaps object is not the same as I would expect. For example, `gmaps.geometry.location.lat` is a `function()` instead of just being a number.

![chinalatlng](https://cloud.githubusercontent.com/assets/1746811/11267954/08653b0c-8eb7-11e5-8001-aedecf6888b4.png)

I checked this in both Firefox and Chrome on your example website.

**Comment by ro-ka** [comment]
That is the pure object as it is returned from Google Maps. So it is the expected response as Google does not provide the lat and lng as pure numbers but functions to retrieve these numbers. 

You can get the pure numbers in `suggest.location`. See the Readme (https://github.com/ubilabs/react-geosuggest#onsuggestselect). Will not alter the Google response as the intention of passing this out was to provide access to the pure Google response.
