### ISSUE TITLE
Powered by google?

### ISSUE THREAD

**Issue by Targun** [ubilabs/react-geosuggest#64]
Do you think it would be a good idea to have a "Powered by Google" at the bottom of the dropdown?

**Comment by ro-ka** [comment]
Why would this be helpful?

**Comment by Targun** [comment]
I thought it would maybe be required by the terms?

https://developers.google.com/places/web-service/policies

**Comment by ro-ka** [comment]
That is correct.

> If your application displays Google Places API Web Service data on a page or view that does not also display a Google Map, you must show a "Powered by Google" logo with that data. For example, if your application displays a list of places on one tab, and a Google Map with those places on another tab, the first tab must show the "Powered by Google" logo.

It doesn’t specify to put this in the autosuggest. With a map you don’t need it at all. Would it be a solution to put it somewhere else in your design, not in the autosuggest?

For example, we use it with a map and a license. Don’t need it then.

**Comment by Targun** [comment]
Ok, great.  Thanks for the clarification.

**Comment by ro-ka** [comment]
You’re welcome! Closing this then.

**Comment by acomito** [comment]
Are you sure about this? 

> If your application displays Google Places API Web Service data on a page or view that does not also display a Google Map, you must show a "Powered by Google" logo with that data

This sounds like it is referring to things like autosuggest boxes. Also, I see most autosuggest packages include the powered by google... although they could be misinterpreting it.

**Comment by Caerostris** [comment]
Yes, as @ro-ka said, this does apply to Geosuggest.
However, the Powered by Google logo does not have to be in the suggest list.
It could be placed anywhere on your website, and is not required at all under certain circumstances.
It is up to the user of the Geosuggest component to implement proper notices when required.

**Comment by rajington** [comment]
I'm currently working on updating this to use the Google Places Details API (to geocode the new Autocomplete results), which REQUIRES an attribution dom element to be used (presumably for premium results). I could simply create an empty div or something, but I'll probably include it as another prop unless you guys had a preference.

I see both sides of the responsibility argument above. On one hand you want to handle as much for the user as possible and if the goal is to be similar to what users are coming from (whether it's Google's own `new google.maps.places.Autocomplete(input)` or other third-party implementations) which include `Powered by Google`. On the other hand, the user will still have to update their ToS/Privacy Policy and may in fact want the attribution elsewhere. 

I'll try to include minimal changes to the switch-to-place-details PR, but I might include attribution as a separate PR.

**Comment by ro-ka** [comment]
I understand that it is annoying to add it to the suggest list by hand. 

What about adding the *powered by* to the suggest list and allow to hide it via CSS? Or a prop? Would allow to remove it but is there for those who need it.

// cc @yfr

**Comment by rajington** [comment]
It's just something we had to do manually after we included the package, but it wasn't that difficult and doesn't seem to be brought up that often so maybe I'm overblowing the issue. I sincerely doubt that Google's going to go after the people that forgot either, so I'm cool with it either. Since I no longer need to do that Place Details PR, I wasn't planning on doing a separate one for adding this either but I'd be willing if there was enough demand.

**Comment by ro-ka** [comment]
Then let’s just wait and see if there is demand.  Thanks!   😃

**Comment by franckmaurin** [comment]
Hello all, I think we need to have the possibility to add the copyright. We just received a mail by Google with this lines :

> In particular, your application also violates clause 9.4(b), which requires developers to include “powered by Google” close to the results of Google Maps API queries where we don’t provide an attribution notice automatically.
Please update your implementation so that “powered by Google” is displayed close to the results, as required by the terms of service.
We’re bringing this to your attention so we can work together to make sure your implementation complies with our terms of service. If you’re not able to bring your implementation into compliance with the terms, we will take action to restrict your access to the service.

**Comment by ro-ka** [comment]
That’s annoying.   :/
Can you add the powered by information via CSS to the list? Or position it next to the autocomplete?

**Comment by franckmaurin** [comment]
Yep, I thought I'd do it like this

**Comment by ro-ka** [comment]
Can you provide some example CSS when you’re done? We could add that to the example.

**Comment by franckmaurin** [comment]
Of course :)

**Comment by franckmaurin** [comment]
I finally added theses following styles

```
.geosuggest__suggests-wrapper:after {
  content: '';
  display: block;
  background: url('../../assets/images/powered-by-google.png') right center no-repeat white;
  background-size: 120px 15px;
  border-right: solid 1rem white;
  width: 100%;
  height: 3rem;
}
```

**Comment by ro-ka** [comment]
Cool, thanks a lot!

**Comment by yfr** [comment]
That's cool!

But don't they have a hosted image somewhere on their CDN? Would make it even easier and we could just include it in the defaults.

**Comment by csandman** [comment]
I have an alternative setup using an image pulled directly from Google's server. I also put it inside the select menu:

```css
.geosuggest__suggests:after {
  content: '';
  margin-right: var(--chakra-space-2);
  margin-top: var(--chakra-space-2);
  height: 18px;
  box-sizing: border-box;
  text-align: right;
  display: block;
  background-image: url(https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white3_hdpi.png);
  background-position: right;
  background-repeat: no-repeat;
  background-size: 120px 14px;
}
```
