### ISSUE TITLE
Place Details

### ISSUE THREAD

**Issue by flynfish** [ubilabs/react-geosuggest#67]
If I made a PR for the below functionality, would you consider merging it?

1. new boolean property -> lookupPlaceDetail
2. if above property is true, lookup place details and add response to suggest data for use in the onSuggestSelect callback.

Thoughts?

**Comment by ro-ka** [comment]
Why not handle this in the onSuggestSelect callback? (Just curious.)

**Comment by flynfish** [comment]
yea good point, I wasn't thinking about that obvious option for some reason.

**Comment by ro-ka** [comment]
:)
