### ISSUE TITLE
React-geosuggest with react-formsy

### ISSUE THREAD

**Issue by cornerolive** [ubilabs/react-geosuggest#69]
Hi,

Would be nice to integrate it with react-formsy:

https://github.com/christianalfoni/formsy-react

Regards!

**Comment by ro-ka** [comment]
What would this look like? I haven’t heard of `formsy-react` before.

**Comment by ro-ka** [comment]
Reopen with information on what would be needed to make it compatible.

**Comment by acomito** [comment]
I'm also interested in this:

https://github.com/mbrookes/formsy-material-ui/issues/122
