### ISSUE TITLE
Styling place name separately from country and city

### ISSUE THREAD

**Issue by oyeanuj** [ubilabs/react-geosuggest#73]
Hi @ro-ka! This library looks great, thank you! For my use-case, I need to style the country (and ideally, the city as well) separately from the place name. 

In your demo, you have only one element in the `li.geosuggest-item`. I was wondering if it is possible today, or possible to add, the ability to distinguish country from the place name and render them with different css classes?

**Comment by ro-ka** [comment]
Thanks, oyeanuj!

You can style the Google Maps suggests via the function [getSuggestLabel](https://github.com/ubilabs/react-geosuggest#getsuggestlabel). For the fixtures, pass in the styled label already on creation.
