### ISSUE TITLE
Support for 'no results found' case

### ISSUE THREAD

**Issue by oyeanuj** [ubilabs/react-geosuggest#74]
Hi @ro-ka! Another n00b question: 

How do you suggest we handle the case where no result is found in the auto-suggest? Is it possible for the input field to just take the string inputted and pass that as a value (or is that already being done?)

**Comment by ro-ka** [comment]
No problem, there are no n00b questions. ;)

It doesn’t return the entered string – the purpose is to always get a geocoded place from the library to use. When using only the inputted string in the geocoding, the chances of a successful geocode are very low as Google already suggests the known stuff.

Or do you have examples of places that don’t get suggested but can be geocoded by Google?

Related to #72.

**Comment by oyeanuj** [comment]
@ro-ka thanks for the response!

I was coming from it more from a UX point of view, where the following three cases might happen and that I would still like to save the input: 

1. Mis-spellings.

2. Places not in Google - this is mainly a problem internationally, where either address or place name doesn't show up in Google. From my personal experience, half the places I look up in India might not show up accurately but people around know the place (and hence important to store the place name).

3. New places, or ones which have psuedo names that they might want to use (again known and understood to the relevant groups even if they can't be geo-coded).

This option would enable the library to provide for input when there are other issues with Google libraries.

What do you think?

**Comment by ro-ka** [comment]
I understand the case. The main purpose is to return a geocoded place to work with. I’m not sure how to integrate the non-geocoding found case.

Possibilities:
* Default is a strict mode that will only return geocoded places.
* A non-strict mode could do this:
  * Geocode the input string on `enter` when nothing is selected.
  * Return geocoded result if something got found.
  * Return without non-geocoded place in case nothing could be geocoded.

Does that make sense?

**Comment by oyeanuj** [comment]
Yes, I think that would work well as it keeps it backward-compatible but provides options to those in need :) 

The only question that I have - 
> Geocode the input string on enter when nothing is selected.
Wondering if the interaction should only be bound to `enter`. What would you think of having the last row always be the address or a label like "Custom Address" and clicking on that gives you the input string as well?

**Comment by ro-ka** [comment]
Hm, good question. As there was the request for a submit button in #72, which is the same thing we are talking about here, I’m not sure what to prefer.

A submit button seems to be more standard, but can be confusing. When selecting a suggestion from the dropdown, the submit button is irritating as it doesn’t have any extra functionality. But custom address can be irritation, too.

Will think about that…

**Comment by iam4x** [comment]
I'm using `react-geosuggest` to validate complete street_address, here's my code:

```javascript
const filterResults = ({ types }) => !types.includes('street_address')

function SearchLocation(props: Props) {
  const { placeholder, onChange, initialValue, children, precise } = props

    return (
      <div className='search-location'>
        <Geosuggest
          placeholder={ placeholder }
          onSuggestSelect={ (value) => handleChange(value, onChange) }
          initialValue={ initialValue || emptyString }
          types={ precise ? [ 'address' ] : [] }
          skipSuggest={ precise ? filterResults : noop } />
        { children }
      </div>
    )
}
```

The filter is pretty aggressive and the user must enter an address starting with a number, would be great to display a message when there's no suggestions :+1: 

Right now, I've wrapped the component to do it myself. If you are ready for a PR @ro-ka I can do it :+1:

**Comment by oyeanuj** [comment]
> The filter is pretty aggressive and the user must enter an address starting with a number, would be great to display a message when there's no suggestions 

That message could be a custom string formed from the input itself. 

+1 to @iam4x volunteering for the PR!


> But custom address can be irritation, too.
@ro-ka Increasingly, I see this behavior in a lot of places which have address auto-complete since there will always be inputs not on google.

**Comment by ro-ka** [comment]
@iam4x If you like to add a PR that would be great!  :)

**Comment by ro-ka** [comment]
Any progress on this?

**Comment by dimafeldman** [comment]
I needed a similar functionality too, so here's my PR:
added support for providing a callback when no results found, by simply passing the onSuggestNoResults prop
https://github.com/ubilabs/react-geosuggest/pull/167

**Comment by oyeanuj** [comment]
This is awesome, thanks @dimafeldman!

**Comment by ro-ka** [comment]
The PR #167 got merged.

**Comment by oyeanuj** [comment]
@ro-ka Revisiting this, as I was testing some old code and realized that the #167 by @dimafeldman (thank you for that!) only solves part of the issue. That PR allows the developer to get the string entered through the callback function. 

But the other part of this issue was what I think #72 and @amanofscience are also referring to: some way to have a custom label in the dropdown which can say "Add [user-input]", clicking on which would fire the callback to `onSuggestNoResults` added by @dimafeldman. 

I was thinking something along the lines of `getSuggestLabel`, like `getSuggestNoResultLabel`? Or do you think we can somehow use that method in this case?
