### ISSUE TITLE
If i set types like 'country' or 'cities' nothing is returned

### ISSUE THREAD

**Issue by Xurma2** [ubilabs/react-geosuggest#77]
Just null in suggestsGoogle
```
	let types    = [
			'country'
		];
	<Geosuggest types={types}/>
```

**Comment by ro-ka** [comment]
You mean there is no suggest ever returned?

**Comment by Xurma2** [comment]
Yes

**Comment by ro-ka** [comment]
I tried and indeed it doesn’t return anything. But as the parameters are passed through directly to the Google Maps API, I cannot do anything about this. Google returns `null` already… Maybe create an issue there?

**Comment by fedysalah** [comment]
let types    = [
            '(country)'
        ];
    <Geosuggest types={types}/>

seem to wok for me got info from http://codetheory.in/google-place-api-autocomplete-service-in-android-application/
