### ISSUE TITLE
Using with redux-form

### ISSUE THREAD

**Issue by hannupekka** [ubilabs/react-geosuggest#78]
Im not sure if this really is this projects problem, but I have a form that uses this component as one of it's fields:
```jsx
<Geosuggest onChange={this.onChange.bind(this)}
```

Form is validated using https://github.com/erikras/redux-form which seems to capture `onChange` events of this component somehow since my handler is not being called. 

I guess this is because this project does not use prefixed `onChange` property?

**Comment by hannupekka** [comment]
Managed to get around this by wrapping `Geosuggest` in additional div:
```jsx
<div onChange={this.onChange.bind(this)}>
    <Geosuggest onSuggestSelect={this.onSuggestSelect.bind(this)} {...location} />
</div>
```

**Comment by ro-ka** [comment]
Great!

In general: Is it a problem that we’re using `onChange`?
