### ISSUE TITLE
Support adding class name(s) to the input element

### ISSUE THREAD

**Issue by nathanmarks** [ubilabs/react-geosuggest#8]
Any interest in adding this in? Would be handy

**Comment by ro-ka** [comment]
Could be helpfull, yes. Would be setting an additional class on the container enough? Or do you want to change the classname at all?

**Comment by nathanmarks** [comment]
Either or... the latter being a little more useful.

**Comment by ro-ka** [comment]
Normally it should be enough to add a class to the container as the rest is self-contained in the module. Or is there a case where you’ll need CSS access to the list or suggested items other than the default classes?

**Comment by ro-ka** [comment]
*Bump* ;)

**Comment by ro-ka** [comment]
Released in `1.4.0`. You can now add an additional `className`. See the Readme: https://github.com/ubilabs/react-geosuggest#classname
