### ISSUE TITLE
1.16.0 module build requiring modules incorrectly

### ISSUE THREAD

**Issue by DullReferenceException** [ubilabs/react-geosuggest#89]
Our application pulled in 1.16.0 of this module, and we get an error when importing:

> Cannot find module './input.jsx'

I ran `prepublish` on this module, and the transpiled `/module/Geosuggest.js` has the expression `require('./index.jsx')`, but the transpiled file is actually named `index.js`.

**Comment by catskul** [comment]
Ditto.

**Comment by DullReferenceException** [comment]
Something like this should fix it:

https://github.com/ubilabs/react-geosuggest/pull/90

**Comment by idolize** [comment]
Same - 1.16.0 is currently unusable :cry:

@ro-ka

**Comment by ro-ka** [comment]
I’m sorry, oversaw that. Thanks for the PR! Will need more tests for all the different cases. Does it work now?

**Comment by idolize** [comment]
@ro-ka It's working - thanks!
