### ISSUE TITLE
Allowed Input Attributes don't match the ones from React

### ISSUE THREAD

**Issue by maxired** [ubilabs/react-geosuggest#93]
React documentation says 

> These standard attributes are supported: 
> ```
> accept acceptCharset accessKey action allowFullScreen allowTransparency alt
> async autoComplete autoFocus autoPlay capture cellPadding cellSpacing challenge
> charSet checked classID className colSpan cols content contentEditable
> contextMenu controls coords crossOrigin data dateTime default defer dir
> disabled download draggable encType form formAction formEncType formMethod
> formNoValidate formTarget frameBorder headers height hidden high href hrefLang
> htmlFor httpEquiv icon id inputMode integrity is keyParams keyType kind label
> lang list loop low manifest marginHeight marginWidth max maxLength media
> mediaGroup method min minLength multiple muted name noValidate nonce open
> optimum pattern placeholder poster preload radioGroup readOnly rel required
> reversed role rowSpan rows sandbox scope scoped scrolling seamless selected
> shape size sizes span spellCheck src srcDoc srcLang srcSet start step style
> summary tabIndex target title type useMap value width wmode wrapp```

your current list is :
```
autocapitalize autocomplete autocorrect autoFocus autosave disabled form formaction
formenctype formmethod formnovalidate formtarget height id inputmode maxlength maxlength
name pattern placeholder readonly required selectionDirection size spellcheck tabindex
```

Obviously, the React  list is longer, but that is not a problem.
The problem is about stuff present in your list that are not handled by React.
For example `autocapitalize`.
Something else that you should be carefull, is the use of capital letter or not.
For example, React allows ` autoComplete`, but you allow `autocomplete`.
This lead in stuff not being propagated.

**Comment by ro-ka** [comment]
Thanks! I updated the list. Released in `1.18.1`.

**Comment by romseguy** [comment]
`title` is missing from https://github.com/ubilabs/react-geosuggest/blob/master/src/filter-input-attributes.js

**Comment by ro-ka** [comment]
Thanks, will be added!
