### ISSUE TITLE
Support for custom Input markup

### ISSUE THREAD

**Issue by jramcast** [ubilabs/react-geosuggest#96]
Hi!

I was thinking of developing some sort of option that allows the component to render a custom markup for the input. For example, I need to render a Material Design input that also needs a label element, something like:

```html
<div class="input-field">
     <input placeholder="Placeholder" id="first_name" type="text" class="validate">
     <label for="first_name">First Name</label>
 </div>
```

How do you think we could approach this?

Thanks!

**Comment by ro-ka** [comment]
You can style the element as you like. The label doesn’t have to be included in the component, you can render the label next to the component and use the `id` prop on the Component.

Example JSX setup:

```jsx
<div class="input-field">
     <Geosuggest placeholder="Placeholder" id="first_name" className="validate" />
     <label for="first_name">First Name</label>
 </div>
```

**Comment by jramcast** [comment]
Right. Didn't think about that. Thx!

**Comment by ro-ka** [comment]
:)
